actor:
  T: 1019
  bits_per_feature: 7
  device: CPU
  nr_of_classes: 2
  nr_of_clauses: 1120
  number_of_state_bits_ta: 3
  s: 2.77
  seed: 42
  weighted_clauses: false
algorithm: TM_DDPG_2
batch_size: 64
critic:
  T: 1116
  bits_per_feature: 12
  device: CPU
  nr_of_clauses: 1450
  number_of_state_bits_ta: 9
  s: 4.66
  seed: 42
  weighted_clauses: false
  y_max: 70
  y_min: 20
epochs: 3
exploration_prob_decay: 0.001
exploration_prob_init: 1.0
gamma: 0.992
save: true
soft_update_type: soft_update_1
test_freq: 1
update_grad: 0.205
