wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1707263469.12345
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.0
      5: 0.16.3
      8:
      - 3
      - 5
      13: windows-amd64
gamma:
  desc: null
  value: 0.6806324304635343
nr_of_clauses:
  desc: null
  value: 1704
number_of_state_bits_ta:
  desc: null
  value: 3
specificity:
  desc: null
  value: 6.2589590683854475
threshold:
  desc: null
  value: 0.3776101190670469
total_bits_per_feature:
  desc: null
  value: 9
update_freq:
  desc: null
  value: 12
y_max:
  desc: null
  value: 61
y_min:
  desc: null
  value: 20
