action_space_size: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  AgAAAAAAAAA=
actor:
  T: 1800
  bits_per_feature: 4
  device: CPU
  nr_of_clauses: 2000
  number_of_state_bits_ta: 4
  s: 3.68
  seed: 42
algorithm: TAC_a
batch_size: 16
buffer_size: 10000
clause_update_p: 0.05
critic:
  T: 1713
  bits_per_feature: 4
  device: CPU
  max_update_p: 1.0
  nr_of_clauses: 2000
  number_of_state_bits_ta: 4
  s: 3.47
  seed: 42
  weighted_clauses: false
  y_max: 130
  y_min: 20
dataset_file_name: cartpole_obs_data
env_name: Cartpole
epsilon_decay: 0.001
epsilon_init: 1.0
gamma: 0.99
obs_space_size: 4
sampling_iterations: 6
save: true
soft_update_type: soft_update_a
test_freq: 1
threshold: -495
