action_space_size: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  AgAAAAAAAAA=
actor:
  T: 1012
  bits_per_feature: 8
  device: CPU
  nr_of_clauses: 1100
  number_of_state_bits_ta: 3
  s: 4.8800000000000034
  seed: 42
algorithm: TAC_a
batch_size: 6
buffer_size: 17500
clause_update_p: 0.417
critic:
  T: 874
  bits_per_feature: 6
  device: CPU
  max_update_p: 0.069
  nr_of_clauses: 1650
  number_of_state_bits_ta: 3
  s: 9.740000000000007
  seed: 42
  y_max: 110
  y_min: 20
dataset_file_name: cartpole_obs_data
env_name: Cartpole
epsilon_decay: 0.001
epsilon_init: 0.8
gamma: 0.99
n_steps: 85
obs_space_size: 4
sampling_iterations: 64
save: true
soft_update_type: soft_update_a
test_freq: 1
threshold: 20
