T: 504
algorithm: TM_PPO
batch_size: 96
bits_per_feature: 12
clip: 0.031
comment: --Does not use normalization--
device: CPU
epochs: 2
gamma: 0.941
lam: 0.98
nr_of_clauses: 1030
number_of_state_bits_ta: 3
s: 1.62
save: true
seed: 42
test_freq: 1
weighted_clauses: false
y_max: 100.0
y_min: 0.0
