T: 359
algorithm: Double_TMQN
batch_size: 64
bits_per_feature: 6
buffer_size: 3000
device: CPU
dynamic_memory: false
epochs: 4
exploration_prob_decay: 0.001
exploration_prob_init: 1.0
gamma: 0.974
min_feedback_p: 1.0
nr_of_clauses: 1160
nr_of_episodes: 10000
nr_of_steps: 2615939
number_of_state_bits_ta: 7
s: 9.79
save: true
seed: 42
soft_update_type: soft_update_2
test_freq: 1
update_freq: 2
update_grad: 0.05
weighted_clauses: false
y_max: 75
y_min: 35
