action_space_size: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  AwAAAAAAAAA=
actor:
  T: 990
  bits_per_feature: 8
  device: CPU
  nr_of_clauses: 1000
  number_of_state_bits_ta: 4
  s: 9.89
  seed: 42
  weighted_clauses: false
algorithm: TAC_b
batch_size: 96
buffer_size: 7500
critic:
  T: 696
  bits_per_feature: 10
  device: CPU
  max_update_p: 0.082
  nr_of_clauses: 1450
  number_of_state_bits_ta: 4
  s: 2.18
  seed: 42
  weighted_clauses: false
  y_max: -30
  y_min: -80
dataset_file_name: acrobot_obs_data
env_name: acrobot
epochs: 2
exploration_prob_decay: 0.006
exploration_prob_init: 0.6
gamma: 0.962
obs_space_size: 6
save: true
soft_update_type: soft_update_2
test_freq: 1
threshold: -500
update_freq: 3
