T: 1165
action_space_size: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  AwAAAAAAAAA=
algorithm: QTM
batch_size: 96
bits_per_feature: 6
buffer_size: 7000
dataset_file_name: acrobot_obs_data
device: CPU
env_name: acrobot
epochs: 3
exploration_prob_decay: 0.006
exploration_prob_init: 0.7
gamma: 0.977
max_update_p: 0.186
min_update_p: 0
nr_of_clauses: 1240
number_of_state_bits_ta: 8
obs_space_size: 6
s: 1.3700000000000003
save: true
seed: 42
test_freq: 1
threshold: -495
weighted_clauses: false
y_max: -5
y_min: -55
