action_space_size: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  AgAAAAAAAAA=
actor:
  T: 39
  bits_per_feature: 6
  device: CPU
  nr_of_clauses: 1950
  number_of_state_bits_ta: 4
  s: 3.450000000000002
  seed: 42
algorithm: TAAC
critic:
  T: 383
  bits_per_feature: 4
  max_update_p: 0.482
  min_update_p: 0.0
  nr_of_clauses: 1010
  number_of_state_bits_ta: 4
  s: 9.000000000000007
  y_max: 99
  y_min: 0.7000000000000001
dataset_file_name: cartpole_obs_data
device: CPU
env_name: cartpole
epochs: 3
gamma: 1
lam: 0.97
n_timesteps: 672
obs_space_size: 4
save: true
seed: 42
test_freq: 5
threshold: 0
