T: 451
action_space_size: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  AgAAAAAAAAA=
algorithm: QTM
batch_size: 64
bits_per_feature: 5
buffer_size: 6000
dataset_file_name: observation_data
device: CPU
env_name: cartpole
epochs: 3
exploration_prob_decay: 0.009000000000000001
exploration_prob_init: 0.8
gamma: 0.991
max_update_p: 0.5
min_update_p: 0
nr_of_clauses: 960
number_of_state_bits_ta: 3
obs_space_size: 4
s: 5.750000000000004
save: true
seed: 42
test_freq: 1
threshold: 20
weighted_clauses: false
y_max: 70
y_min: 20
