action_space_size: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  AwAAAAAAAAA=
actor:
  T: 629
  bits_per_feature: 6
  max_update_p: 0.016
  min_update_p: 0.0008
  nr_of_clauses: 1850
  number_of_state_bits_ta: 6
  s: 1.76
  y_max: 100
  y_min: 0
algorithm: TPPO
batch_size: 128
critic:
  T: 1045
  bits_per_feature: 10
  max_update_p: 0.075
  min_update_p: 0.0
  nr_of_clauses: 1340
  number_of_state_bits_ta: 7
  s: 1.65
  y_max: -1.0
  y_min: -29.1
dataset_file_name: acrobot_obs_data
device: CPU
env_name: acrobot
epochs: 2
gamma: 0.951
lam: 0.944
n_timesteps: 12
obs_space_size: 6
save: true
seed: 42
test_freq: 1
threshold: -1000
weighted_clauses: false
