wandb_version: 1

a_bits_per_feature:
  value: 9
a_nr_of_clauses:
  value: 1040
a_number_of_state_bits_ta:
  value: 5
a_specificity:
  value: 6.650000000000005
a_t:
  value: 0.8
c_bits_per_feature:
  value: 7
c_nr_of_clauses:
  value: 1750
c_number_of_state_bits_ta:
  value: 4
c_specificity:
  value: 2.220000000000001
c_t:
  value: 0.18000000000000002
c_y_max:
  value: 65
c_y_min:
  value: 30
gamma:
  value: 0.938
update_freq:
  value: 5
