T: 613
action_space_size: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  AwAAAAAAAAA=
algorithm: n_step_Double_QTM_b
batch_size: 48
bits_per_feature: 10
buffer_size: 4000
dataset_file_name: acrobot_obs_data
device: CPU
env_name: acrobot
epochs: 1
exploration_prob_decay: 0.008
exploration_prob_init: 0.7
gamma: 0.93
max_update_p: 0.151
min_update_p: 0
n_steps: 14
nr_of_clauses: 1860
number_of_state_bits_ta: 6
obs_space_size: 6
s: 3.6000000000000023
save: true
seed: 42
soft_update_type: soft_update_2
test_freq: 1
threshold: -495
update_freq: 3
update_grad: -1
weighted_clauses: false
y_max: -10
y_min: -70
