wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709125944.272485
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.0
      5: 0.16.3
      8:
      - 3
      - 5
      13: windows-amd64
batch_size:
  desc: null
  value: 80
bits_per_feature:
  desc: null
  value: 12
buffer_size:
  desc: null
  value: 2000
epochs:
  desc: null
  value: 4
gamma:
  desc: null
  value: 0.9
nr_of_clauses:
  desc: null
  value: 1060
number_of_state_bits_ta:
  desc: null
  value: 9
specificity:
  desc: null
  value: 9.530000000000008
t:
  desc: null
  value: 0.8400000000000001
update_freq:
  desc: null
  value: 9
y_max:
  desc: null
  value: 70
y_min:
  desc: null
  value: 35
