wandb_version: 1

batch_size:
  value: 80
bits_per_feature:
  value: 13
buffer_size:
  value: 1000
epochs:
  value: 3
gamma:
  value: 0.953
n_steps:
  value: 7
nr_of_clauses:
  value: 1100
number_of_state_bits_ta:
  value: 4
specificity:
  value: 6.750000000000005
t:
  value: 0.28
update_freq:
  value: 5
y_max:
  value: 75
y_min:
  value: 20
