wandb_version: 1

batch_size:
  value: 64
bits_per_feature:
  value: 13
buffer_size:
  value: 9000
epochs:
  value: 4
gamma:
  value: 0.955
n_steps:
  value: 17
nr_of_clauses:
  value: 1000
number_of_state_bits_ta:
  value: 6
specificity:
  value: 9.020000000000008
t:
  value: 0.54
update_freq:
  value: 4
y_max:
  value: 70
y_min:
  value: 35
