action_space_size: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  AwAAAAAAAAA=
algorithm: n_step_DQN
batch_size: 64
buffer_size: 5000
c: 1
env_name: acrobot
epochs: 4
exploration_prob_decay: 0.001
exploration_prob_init: 1.0
gamma: 0.99
hidden_size: 128
learning_rate: 0.0003
n_steps: 47
obs_space_size: 6
save: true
test_freq: 50
