T: 1089
action_space_size: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  AgAAAAAAAAA=
algorithm: n_step_Double_QTM_a
batch_size: 64
bits_per_feature: 12
buffer_size: 1000
dataset_file_name: observation_data
device: CPU
env_name: cartpole
epochs: 7
exploration_prob_decay: 0.002
exploration_prob_init: 0.9
gamma: 0.957
max_update_p: 0.139
min_update_p: 0
n_steps: 12
nr_of_clauses: 1100
number_of_state_bits_ta: 5
obs_space_size: 4
s: 9.130000000000008
save: true
seed: 42
soft_update_type: soft_update_1
test_freq: 1
threshold: 20
update_freq: -1
update_grad: 0.173
weighted_clauses: false
y_max: 60
y_min: 20
