wandb_version: 1

batch_size:
  value: 32
bits_per_feature:
  value: 11
buffer_size:
  value: 1000
epochs:
  value: 7
gamma:
  value: 0.964
nr_of_clauses:
  value: 900
number_of_state_bits_ta:
  value: 9
specificity:
  value: 6.280000000000005
t:
  value: 0.8300000000000001
update_freq:
  value: 6
y_max:
  value: 65
y_min:
  value: 25
