wandb_version: 1

batch_size:
  value: 64
bits_per_feature:
  value: 5
buffer_size:
  value: 3000
epochs:
  value: 7
gamma:
  value: 0.973
nr_of_clauses:
  value: 1180
number_of_state_bits_ta:
  value: 3
specificity:
  value: 4.450000000000003
t:
  value: 0.05
update_freq:
  value: 2
y_max:
  value: 70
y_min:
  value: 20
