wandb_version: 1

batch_size:
  value: 32
bits_per_feature:
  value: 10
buffer_size:
  value: 1000
epochs:
  value: 2
gamma:
  value: 0.934
nr_of_clauses:
  value: 900
number_of_state_bits_ta:
  value: 9
specificity:
  value: 3.120000000000002
t:
  value: 0.24
update_freq:
  value: 9
y_max:
  value: 75
y_min:
  value: 35
