wandb_version: 1

batch_size:
  value: 64
bits_per_feature:
  value: 8
buffer_size:
  value: 4500
epochs:
  value: 2
gamma:
  value: 0.994
nr_of_clauses:
  value: 1000
number_of_state_bits_ta:
  value: 5
specificity:
  value: 1.8700000000000008
t:
  value: 0.79
update_freq:
  value: 4
y_max:
  value: 75
y_min:
  value: 30
