wandb_version: 1

batch_size:
  value: 16
bits_per_feature:
  value: 10
buffer_size:
  value: 8500
epochs:
  value: 5
gamma:
  value: 0.959
nr_of_clauses:
  value: 820
number_of_state_bits_ta:
  value: 3
specificity:
  value: 1.03
t:
  value: 0.65
update_freq:
  value: 6
y_max:
  value: 60
y_min:
  value: 20
