wandb_version: 1

batch_size:
  value: 32
bits_per_feature:
  value: 14
buffer_size:
  value: 4500
epochs:
  value: 7
gamma:
  value: 0.942
nr_of_clauses:
  value: 1100
number_of_state_bits_ta:
  value: 8
specificity:
  value: 2.130000000000001
t:
  value: 0.87
update_freq:
  value: 4
y_max:
  value: 70
y_min:
  value: 25
