wandb_version: 1

batch_size:
  value: 32
bits_per_feature:
  value: 7
buffer_size:
  value: 6000
epochs:
  value: 3
gamma:
  value: 0.988
nr_of_clauses:
  value: 980
number_of_state_bits_ta:
  value: 4
specificity:
  value: 4.8800000000000034
t:
  value: 0.61
update_freq:
  value: 3
y_max:
  value: 70
y_min:
  value: 30
