wandb_version: 1

batch_size:
  value: 64
bits_per_feature:
  value: 11
buffer_size:
  value: 2500
epochs:
  value: 3
gamma:
  value: 0.949
nr_of_clauses:
  value: 940
number_of_state_bits_ta:
  value: 6
specificity:
  value: 6.090000000000004
t:
  value: 0.6900000000000001
update_freq:
  value: 6
y_max:
  value: 75
y_min:
  value: 30
