wandb_version: 1

batch_size:
  value: 16
bits_per_feature:
  value: 13
buffer_size:
  value: 1500
epochs:
  value: 1
gamma:
  value: 0.928
nr_of_clauses:
  value: 900
number_of_state_bits_ta:
  value: 9
specificity:
  value: 5.650000000000004
t:
  value: 0.68
update_freq:
  value: 6
y_max:
  value: 75
y_min:
  value: 20
