wandb_version: 1

batch_size:
  value: 80
bits_per_feature:
  value: 10
buffer_size:
  value: 3000
epochs:
  value: 1
gamma:
  value: 0.913
nr_of_clauses:
  value: 1020
number_of_state_bits_ta:
  value: 4
specificity:
  value: 7.050000000000005
t:
  value: 0.97
update_freq:
  value: 6
y_max:
  value: 75
y_min:
  value: 25
