wandb_version: 1

batch_size:
  value: 96
bits_per_feature:
  value: 6
buffer_size:
  value: 500
epochs:
  value: 5
gamma:
  value: 0.918
nr_of_clauses:
  value: 920
number_of_state_bits_ta:
  value: 4
specificity:
  value: 5.110000000000004
t:
  value: 0.86
update_freq:
  value: 8
y_max:
  value: 65
y_min:
  value: 35
