wandb_version: 1

batch_size:
  value: 32
bits_per_feature:
  value: 13
buffer_size:
  value: 9000
epochs:
  value: 1
gamma:
  value: 0.904
nr_of_clauses:
  value: 820
number_of_state_bits_ta:
  value: 3
specificity:
  value: 6.840000000000005
t:
  value: 0.6900000000000001
update_freq:
  value: 6
y_max:
  value: 70
y_min:
  value: 20
