wandb_version: 1

batch_size:
  value: 80
bits_per_feature:
  value: 5
buffer_size:
  value: 6000
epochs:
  value: 5
gamma:
  value: 0.926
nr_of_clauses:
  value: 1180
number_of_state_bits_ta:
  value: 4
specificity:
  value: 7.350000000000006
t:
  value: 0.8200000000000001
update_freq:
  value: 6
y_max:
  value: 60
y_min:
  value: 25
