wandb_version: 1

batch_size:
  value: 32
bits_per_feature:
  value: 10
buffer_size:
  value: 1500
epochs:
  value: 1
gamma:
  value: 0.95
nr_of_clauses:
  value: 1020
number_of_state_bits_ta:
  value: 4
specificity:
  value: 3.8200000000000025
t:
  value: 0.25
update_freq:
  value: 2
y_max:
  value: 70
y_min:
  value: 30
