wandb_version: 1

batch_size:
  value: 80
bits_per_feature:
  value: 12
buffer_size:
  value: 2000
epochs:
  value: 4
gamma:
  value: 0.9
nr_of_clauses:
  value: 1060
number_of_state_bits_ta:
  value: 9
specificity:
  value: 9.530000000000008
t:
  value: 0.8400000000000001
update_freq:
  value: 9
y_max:
  value: 70
y_min:
  value: 35
