wandb_version: 1

batch_size:
  value: 64
bits_per_feature:
  value: 14
buffer_size:
  value: 4500
epochs:
  value: 7
gamma:
  value: 0.946
nr_of_clauses:
  value: 1080
number_of_state_bits_ta:
  value: 8
specificity:
  value: 6.530000000000005
t:
  value: 0.53
update_freq:
  value: 7
y_max:
  value: 60
y_min:
  value: 25
