wandb_version: 1

batch_size:
  value: 16
bits_per_feature:
  value: 10
buffer_size:
  value: 1000
epochs:
  value: 6
gamma:
  value: 0.925
nr_of_clauses:
  value: 1180
number_of_state_bits_ta:
  value: 6
specificity:
  value: 7.320000000000006
t:
  value: 0.61
update_freq:
  value: 6
y_max:
  value: 65
y_min:
  value: 20
