wandb_version: 1

batch_size:
  value: 16
bits_per_feature:
  value: 13
buffer_size:
  value: 4000
epochs:
  value: 6
gamma:
  value: 0.946
nr_of_clauses:
  value: 1020
number_of_state_bits_ta:
  value: 5
specificity:
  value: 7.940000000000007
t:
  value: 0.16
update_freq:
  value: 4
y_max:
  value: 75
y_min:
  value: 25
