wandb_version: 1

batch_size:
  value: 32
bits_per_feature:
  value: 6
buffer_size:
  value: 1000
epochs:
  value: 5
gamma:
  value: 0.932
nr_of_clauses:
  value: 1060
number_of_state_bits_ta:
  value: 6
specificity:
  value: 1.5700000000000005
t:
  value: 0.95
update_freq:
  value: 7
y_max:
  value: 70
y_min:
  value: 30
