wandb_version: 1

batch_size:
  value: 80
bits_per_feature:
  value: 11
buffer_size:
  value: 3000
epochs:
  value: 7
gamma:
  value: 0.99
nr_of_clauses:
  value: 820
number_of_state_bits_ta:
  value: 5
specificity:
  value: 7.690000000000006
t:
  value: 0.34
update_freq:
  value: 5
y_max:
  value: 65
y_min:
  value: 20
