wandb_version: 1

batch_size:
  value: 64
bits_per_feature:
  value: 9
buffer_size:
  value: 500
epochs:
  value: 2
gamma:
  value: 0.91
nr_of_clauses:
  value: 1060
number_of_state_bits_ta:
  value: 7
specificity:
  value: 7.480000000000006
t:
  value: 0.33
update_freq:
  value: 9
y_max:
  value: 60
y_min:
  value: 20
