wandb_version: 1

batch_size:
  value: 32
bits_per_feature:
  value: 9
buffer_size:
  value: 4500
epochs:
  value: 3
gamma:
  value: 0.922
nr_of_clauses:
  value: 800
number_of_state_bits_ta:
  value: 5
specificity:
  value: 1.6700000000000006
t:
  value: 0.85
update_freq:
  value: 5
y_max:
  value: 60
y_min:
  value: 25
