wandb_version: 1

batch_size:
  value: 96
bits_per_feature:
  value: 12
buffer_size:
  value: 6000
epochs:
  value: 3
gamma:
  value: 0.96
nr_of_clauses:
  value: 820
number_of_state_bits_ta:
  value: 3
specificity:
  value: 5.850000000000004
t:
  value: 0.5800000000000001
update_freq:
  value: 7
y_max:
  value: 65
y_min:
  value: 20
