wandb_version: 1

batch_size:
  value: 96
bits_per_feature:
  value: 5
buffer_size:
  value: 2500
epochs:
  value: 1
gamma:
  value: 0.967
nr_of_clauses:
  value: 1140
number_of_state_bits_ta:
  value: 7
specificity:
  value: 1.2600000000000002
t:
  value: 0.13
update_freq:
  value: 5
y_max:
  value: 70
y_min:
  value: 35
