wandb_version: 1

batch_size:
  value: 48
bits_per_feature:
  value: 9
buffer_size:
  value: 1000
epochs:
  value: 5
gamma:
  value: 0.917
nr_of_clauses:
  value: 1020
number_of_state_bits_ta:
  value: 6
specificity:
  value: 7.740000000000005
t:
  value: 0.9
update_freq:
  value: 4
y_max:
  value: 75
y_min:
  value: 35
