wandb_version: 1

batch_size:
  value: 64
bits_per_feature:
  value: 10
buffer_size:
  value: 5000
epochs:
  value: 2
gamma:
  value: 0.932
nr_of_clauses:
  value: 1120
number_of_state_bits_ta:
  value: 8
specificity:
  value: 3.340000000000002
t:
  value: 0.28
update_freq:
  value: 3
y_max:
  value: 60
y_min:
  value: 25
