wandb_version: 1

batch_size:
  value: 64
bits_per_feature:
  value: 6
buffer_size:
  value: 5000
epochs:
  value: 2
gamma:
  value: 0.979
nr_of_clauses:
  value: 1120
number_of_state_bits_ta:
  value: 4
specificity:
  value: 5.710000000000004
t:
  value: 0.46
update_freq:
  value: 5
y_max:
  value: 65
y_min:
  value: 30
