wandb_version: 1

batch_size:
  value: 64
bits_per_feature:
  value: 10
buffer_size:
  value: 3500
epochs:
  value: 3
gamma:
  value: 0.995
nr_of_clauses:
  value: 800
number_of_state_bits_ta:
  value: 5
specificity:
  value: 2.000000000000001
t:
  value: 0.74
update_freq:
  value: 7
y_max:
  value: 65
y_min:
  value: 20
