action_space_size: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  AgAAAAAAAAA=
actor:
  T: 336
  bits_per_feature: 9
  device: CPU
  nr_of_clauses: 960
  number_of_state_bits_ta: 3
  s: 1.41
  seed: 42
  weighted_clauses: false
algorithm: TAC_a
batch_size: 112
buffer_size: 2500
critic:
  T: 1017
  bits_per_feature: 5
  device: CPU
  max_update_p: 0.027
  nr_of_clauses: 1850
  number_of_state_bits_ta: 3
  s: 2.59
  seed: 42
  weighted_clauses: false
  y_max: 65
  y_min: 35
dataset_file_name: observation_data
env_name: cartpole
epochs: 4
exploration_prob_decay: 0.002
exploration_prob_init: 0.9
gamma: 0.954
obs_space_size: 4
save: true
soft_update_type: soft_update_1
test_freq: 1
threshold: 0
update_grad: 0.677
