wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1707314256.18625
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.0
      5: 0.16.3
      8:
      - 3
      - 5
      13: windows-amd64
gamma:
  desc: null
  value: 0.9291967781374828
nr_of_clauses:
  desc: null
  value: 335
number_of_state_bits_ta:
  desc: null
  value: 19
specificity:
  desc: null
  value: 9.036639433765838
threshold:
  desc: null
  value: 0.43325010882600545
total_bits_per_feature:
  desc: null
  value: 2
update_freq:
  desc: null
  value: 22
y_max:
  desc: null
  value: 79
y_min:
  desc: null
  value: 39
