wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709018873.455584
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.0
      5: 0.16.3
      8:
      - 3
      - 5
      13: windows-amd64
a_bits_per_feature:
  desc: null
  value: 9
a_nr_of_clauses:
  desc: null
  value: 900
a_number_of_state_bits_ta:
  desc: null
  value: 7
a_specificity:
  desc: null
  value: 2.5500000000000016
a_t:
  desc: null
  value: 0.36000000000000004
c_bits_per_feature:
  desc: null
  value: 14
c_nr_of_clauses:
  desc: null
  value: 1950
c_number_of_state_bits_ta:
  desc: null
  value: 7
c_specificity:
  desc: null
  value: 4.840000000000003
c_t:
  desc: null
  value: 0.22
c_y_max:
  desc: null
  value: 70
c_y_min:
  desc: null
  value: 25
gamma:
  desc: null
  value: 0.969
update_freq:
  desc: null
  value: 3
