wandb_version: 1

a_bits_per_feature:
  value: 8
a_nr_of_clauses:
  value: 800
a_number_of_state_bits_ta:
  value: 5
a_specificity:
  value: 4.310000000000003
a_t:
  value: 0.15000000000000002
c_bits_per_feature:
  value: 9
c_nr_of_clauses:
  value: 1500
c_number_of_state_bits_ta:
  value: 7
c_specificity:
  value: 3.570000000000002
c_t:
  value: 0.17
c_y_max:
  value: 75
c_y_min:
  value: 25
gamma:
  value: 0.902
update_freq:
  value: 6
