wandb_version: 1

a_bits_per_feature:
  value: 8
a_nr_of_clauses:
  value: 860
a_number_of_state_bits_ta:
  value: 3
a_specificity:
  value: 6.060000000000004
a_t:
  value: 0.8200000000000001
c_bits_per_feature:
  value: 7
c_nr_of_clauses:
  value: 1250
c_number_of_state_bits_ta:
  value: 3
c_specificity:
  value: 3.410000000000002
c_t:
  value: 0.65
c_y_max:
  value: 60
c_y_min:
  value: 20
gamma:
  value: 0.976
update_freq:
  value: 7
