wandb_version: 1

a_bits_per_feature:
  value: 10
a_nr_of_clauses:
  value: 960
a_number_of_state_bits_ta:
  value: 5
a_specificity:
  value: 4.940000000000003
a_t:
  value: 0.36000000000000004
c_bits_per_feature:
  value: 6
c_nr_of_clauses:
  value: 1700
c_number_of_state_bits_ta:
  value: 8
c_specificity:
  value: 5.740000000000004
c_t:
  value: 0.99
c_y_max:
  value: 65
c_y_min:
  value: 30
gamma:
  value: 0.984
update_freq:
  value: 5
