wandb_version: 1

a_bits_per_feature:
  value: 13
a_nr_of_clauses:
  value: 1140
a_number_of_state_bits_ta:
  value: 3
a_specificity:
  value: 5.010000000000003
a_t:
  value: 0.14
c_bits_per_feature:
  value: 6
c_nr_of_clauses:
  value: 1950
c_number_of_state_bits_ta:
  value: 5
c_specificity:
  value: 1.7400000000000009
c_t:
  value: 0.55
c_y_max:
  value: 60
c_y_min:
  value: 35
gamma:
  value: 0.955
update_freq:
  value: 6
