wandb_version: 1

a_bits_per_feature:
  value: 5
a_nr_of_clauses:
  value: 1060
a_number_of_state_bits_ta:
  value: 9
a_specificity:
  value: 6.130000000000004
a_t:
  value: 0.44
c_bits_per_feature:
  value: 13
c_nr_of_clauses:
  value: 1900
c_number_of_state_bits_ta:
  value: 6
c_specificity:
  value: 5.1300000000000034
c_t:
  value: 0.87
c_y_max:
  value: 70
c_y_min:
  value: 35
gamma:
  value: 0.926
update_freq:
  value: 4
