wandb_version: 1

a_bits_per_feature:
  value: 13
a_nr_of_clauses:
  value: 1120
a_number_of_state_bits_ta:
  value: 8
a_specificity:
  value: 2.8800000000000017
a_t:
  value: 0.18000000000000002
c_bits_per_feature:
  value: 5
c_nr_of_clauses:
  value: 1000
c_number_of_state_bits_ta:
  value: 9
c_specificity:
  value: 9.990000000000007
c_t:
  value: 0.5
c_y_max:
  value: 75
c_y_min:
  value: 30
gamma:
  value: 0.948
update_freq:
  value: 4
