wandb_version: 1

a_bits_per_feature:
  value: 10
a_nr_of_clauses:
  value: 1060
a_number_of_state_bits_ta:
  value: 7
a_specificity:
  value: 5.1300000000000034
a_t:
  value: 0.9
c_bits_per_feature:
  value: 5
c_nr_of_clauses:
  value: 1650
c_number_of_state_bits_ta:
  value: 8
c_specificity:
  value: 3.240000000000002
c_t:
  value: 0.8200000000000001
c_y_max:
  value: 65
c_y_min:
  value: 30
gamma:
  value: 0.992
update_freq:
  value: 4
