wandb_version: 1

a_bits_per_feature:
  value: 7
a_nr_of_clauses:
  value: 1000
a_number_of_state_bits_ta:
  value: 4
a_specificity:
  value: 5.700000000000005
a_t:
  value: 0.9
c_bits_per_feature:
  value: 6
c_nr_of_clauses:
  value: 1300
c_number_of_state_bits_ta:
  value: 9
c_specificity:
  value: 6.130000000000004
c_t:
  value: 0.77
c_y_max:
  value: 75
c_y_min:
  value: 25
gamma:
  value: 0.923
update_freq:
  value: 6
