wandb_version: 1

a_bits_per_feature:
  value: 7
a_nr_of_clauses:
  value: 800
a_number_of_state_bits_ta:
  value: 7
a_specificity:
  value: 5.700000000000005
a_t:
  value: 0.4
c_bits_per_feature:
  value: 12
c_nr_of_clauses:
  value: 1800
c_number_of_state_bits_ta:
  value: 9
c_specificity:
  value: 8.010000000000005
c_t:
  value: 0.21
c_y_max:
  value: 60
c_y_min:
  value: 35
gamma:
  value: 0.944
update_freq:
  value: 6
