wandb_version: 1

a_bits_per_feature:
  value: 14
a_nr_of_clauses:
  value: 800
a_number_of_state_bits_ta:
  value: 6
a_specificity:
  value: 1.2000000000000002
a_t:
  value: 0.25
c_bits_per_feature:
  value: 6
c_nr_of_clauses:
  value: 850
c_number_of_state_bits_ta:
  value: 8
c_specificity:
  value: 5.190000000000004
c_t:
  value: 0.36000000000000004
c_y_max:
  value: 65
c_y_min:
  value: 30
gamma:
  value: 0.932
update_freq:
  value: 4
