wandb_version: 1

a_bits_per_feature:
  value: 9
a_nr_of_clauses:
  value: 1140
a_number_of_state_bits_ta:
  value: 4
a_specificity:
  value: 2.7400000000000015
a_t:
  value: 0.33
c_bits_per_feature:
  value: 13
c_nr_of_clauses:
  value: 1950
c_number_of_state_bits_ta:
  value: 7
c_specificity:
  value: 9.090000000000009
c_t:
  value: 0.56
c_y_max:
  value: 65
c_y_min:
  value: 35
gamma:
  value: 0.969
update_freq:
  value: 7
