wandb_version: 1

a_bits_per_feature:
  value: 8
a_nr_of_clauses:
  value: 840
a_number_of_state_bits_ta:
  value: 7
a_specificity:
  value: 1.8100000000000007
a_t:
  value: 0.74
c_bits_per_feature:
  value: 10
c_nr_of_clauses:
  value: 1100
c_number_of_state_bits_ta:
  value: 4
c_specificity:
  value: 7.800000000000006
c_t:
  value: 0.6
c_y_max:
  value: 75
c_y_min:
  value: 25
gamma:
  value: 0.927
update_freq:
  value: 5
