wandb_version: 1

a_bits_per_feature:
  value: 7
a_nr_of_clauses:
  value: 900
a_number_of_state_bits_ta:
  value: 8
a_specificity:
  value: 5.900000000000004
a_t:
  value: 0.86
c_bits_per_feature:
  value: 5
c_nr_of_clauses:
  value: 900
c_number_of_state_bits_ta:
  value: 6
c_specificity:
  value: 2.870000000000002
c_t:
  value: 0.48
c_y_max:
  value: 65
c_y_min:
  value: 20
gamma:
  value: 0.901
update_freq:
  value: 7
