wandb_version: 1

a_bits_per_feature:
  value: 14
a_nr_of_clauses:
  value: 900
a_number_of_state_bits_ta:
  value: 8
a_specificity:
  value: 6.0800000000000045
a_t:
  value: 0.38
c_bits_per_feature:
  value: 14
c_nr_of_clauses:
  value: 1200
c_number_of_state_bits_ta:
  value: 5
c_specificity:
  value: 4.370000000000003
c_t:
  value: 0.15000000000000002
c_y_max:
  value: 65
c_y_min:
  value: 20
gamma:
  value: 0.983
update_freq:
  value: 3
