wandb_version: 1

a_bits_per_feature:
  value: 7
a_nr_of_clauses:
  value: 920
a_number_of_state_bits_ta:
  value: 7
a_specificity:
  value: 3.1300000000000017
a_t:
  value: 0.59
c_bits_per_feature:
  value: 6
c_nr_of_clauses:
  value: 1500
c_number_of_state_bits_ta:
  value: 9
c_specificity:
  value: 7.350000000000006
c_t:
  value: 0.55
c_y_max:
  value: 65
c_y_min:
  value: 35
gamma:
  value: 0.95
update_freq:
  value: 5
