wandb_version: 1

a_bits_per_feature:
  value: 10
a_nr_of_clauses:
  value: 1140
a_number_of_state_bits_ta:
  value: 8
a_specificity:
  value: 6.630000000000005
a_t:
  value: 0.81
c_bits_per_feature:
  value: 9
c_nr_of_clauses:
  value: 1700
c_number_of_state_bits_ta:
  value: 5
c_specificity:
  value: 4.410000000000003
c_t:
  value: 0.76
c_y_max:
  value: 65
c_y_min:
  value: 35
gamma:
  value: 0.944
update_freq:
  value: 4
