wandb_version: 1

a_bits_per_feature:
  value: 7
a_nr_of_clauses:
  value: 1040
a_number_of_state_bits_ta:
  value: 9
a_specificity:
  value: 8.600000000000007
a_t:
  value: 0.52
c_bits_per_feature:
  value: 11
c_nr_of_clauses:
  value: 1200
c_number_of_state_bits_ta:
  value: 6
c_specificity:
  value: 4.4200000000000035
c_t:
  value: 0.6
c_y_max:
  value: 60
c_y_min:
  value: 30
gamma:
  value: 0.918
update_freq:
  value: 3
