wandb_version: 1

a_bits_per_feature:
  value: 13
a_nr_of_clauses:
  value: 900
a_number_of_state_bits_ta:
  value: 6
a_specificity:
  value: 6.160000000000005
a_t:
  value: 0.060000000000000005
c_bits_per_feature:
  value: 9
c_nr_of_clauses:
  value: 1450
c_number_of_state_bits_ta:
  value: 7
c_specificity:
  value: 6.3700000000000045
c_t:
  value: 0.62
c_y_max:
  value: 70
c_y_min:
  value: 35
gamma:
  value: 0.916
update_freq:
  value: 6
