wandb_version: 1

a_bits_per_feature:
  value: 7
a_nr_of_clauses:
  value: 1160
a_number_of_state_bits_ta:
  value: 9
a_specificity:
  value: 4.5000000000000036
a_t:
  value: 0.52
c_bits_per_feature:
  value: 7
c_nr_of_clauses:
  value: 1150
c_number_of_state_bits_ta:
  value: 8
c_specificity:
  value: 6.340000000000005
c_t:
  value: 0.54
c_y_max:
  value: 65
c_y_min:
  value: 30
gamma:
  value: 0.906
update_freq:
  value: 6
