wandb_version: 1

a_bits_per_feature:
  value: 13
a_nr_of_clauses:
  value: 880
a_number_of_state_bits_ta:
  value: 9
a_specificity:
  value: 7.690000000000006
a_t:
  value: 0.62
c_bits_per_feature:
  value: 12
c_nr_of_clauses:
  value: 1450
c_number_of_state_bits_ta:
  value: 3
c_specificity:
  value: 2.070000000000001
c_t:
  value: 0.46
c_y_max:
  value: 75
c_y_min:
  value: 35
gamma:
  value: 0.939
update_freq:
  value: 5
