wandb_version: 1

a_bits_per_feature:
  value: 14
a_nr_of_clauses:
  value: 820
a_number_of_state_bits_ta:
  value: 4
a_specificity:
  value: 4.000000000000003
a_t:
  value: 0.34
c_bits_per_feature:
  value: 14
c_nr_of_clauses:
  value: 900
c_number_of_state_bits_ta:
  value: 8
c_specificity:
  value: 5.690000000000004
c_t:
  value: 0.41
c_y_max:
  value: 60
c_y_min:
  value: 20
gamma:
  value: 0.94
update_freq:
  value: 7
