wandb_version: 1

a_bits_per_feature:
  value: 13
a_nr_of_clauses:
  value: 920
a_number_of_state_bits_ta:
  value: 9
a_specificity:
  value: 5.5000000000000036
a_t:
  value: 0.62
c_bits_per_feature:
  value: 10
c_nr_of_clauses:
  value: 900
c_number_of_state_bits_ta:
  value: 5
c_specificity:
  value: 3.4700000000000024
c_t:
  value: 0.36000000000000004
c_y_max:
  value: 70
c_y_min:
  value: 35
gamma:
  value: 0.983
update_freq:
  value: 5
