wandb_version: 1

a_bits_per_feature:
  value: 7
a_nr_of_clauses:
  value: 960
a_number_of_state_bits_ta:
  value: 5
a_specificity:
  value: 7.960000000000006
a_t:
  value: 0.34
c_bits_per_feature:
  value: 11
c_nr_of_clauses:
  value: 1300
c_number_of_state_bits_ta:
  value: 4
c_specificity:
  value: 3.7400000000000024
c_t:
  value: 0.06999999999999999
c_y_max:
  value: 60
c_y_min:
  value: 35
gamma:
  value: 0.969
update_freq:
  value: 5
