wandb_version: 1

a_bits_per_feature:
  value: 5
a_nr_of_clauses:
  value: 1120
a_number_of_state_bits_ta:
  value: 4
a_specificity:
  value: 4.0500000000000025
a_t:
  value: 0.41
c_bits_per_feature:
  value: 5
c_nr_of_clauses:
  value: 1200
c_number_of_state_bits_ta:
  value: 5
c_specificity:
  value: 2.000000000000001
c_t:
  value: 0.41
c_y_max:
  value: 60
c_y_min:
  value: 35
gamma:
  value: 0.969
update_freq:
  value: 5
