wandb_version: 1

a_bits_per_feature:
  value: 14
a_nr_of_clauses:
  value: 900
a_number_of_state_bits_ta:
  value: 3
a_specificity:
  value: 8.400000000000006
a_t:
  value: 0.26
c_bits_per_feature:
  value: 14
c_nr_of_clauses:
  value: 850
c_number_of_state_bits_ta:
  value: 8
c_specificity:
  value: 8.220000000000006
c_t:
  value: 0.43
c_y_max:
  value: 70
c_y_min:
  value: 25
gamma:
  value: 0.9
update_freq:
  value: 4
