wandb_version: 1

a_bits_per_feature:
  value: 9
a_nr_of_clauses:
  value: 980
a_number_of_state_bits_ta:
  value: 5
a_specificity:
  value: 9.760000000000009
a_t:
  value: 0.23
c_bits_per_feature:
  value: 5
c_nr_of_clauses:
  value: 1100
c_number_of_state_bits_ta:
  value: 9
c_specificity:
  value: 9.170000000000009
c_t:
  value: 0.87
c_y_max:
  value: 75
c_y_min:
  value: 25
gamma:
  value: 0.94
update_freq:
  value: 6
