wandb_version: 1

a_bits_per_feature:
  value: 9
a_nr_of_clauses:
  value: 900
a_number_of_state_bits_ta:
  value: 7
a_specificity:
  value: 2.5500000000000016
a_t:
  value: 0.36000000000000004
c_bits_per_feature:
  value: 14
c_nr_of_clauses:
  value: 1950
c_number_of_state_bits_ta:
  value: 7
c_specificity:
  value: 4.840000000000003
c_t:
  value: 0.22
c_y_max:
  value: 70
c_y_min:
  value: 25
gamma:
  value: 0.969
update_freq:
  value: 3
