wandb_version: 1

a_bits_per_feature:
  value: 11
a_nr_of_clauses:
  value: 1040
a_number_of_state_bits_ta:
  value: 4
a_specificity:
  value: 4.820000000000004
a_t:
  value: 0.38
c_bits_per_feature:
  value: 5
c_nr_of_clauses:
  value: 1400
c_number_of_state_bits_ta:
  value: 5
c_specificity:
  value: 1.6400000000000006
c_t:
  value: 0.79
c_y_max:
  value: 65
c_y_min:
  value: 35
gamma:
  value: 0.947
update_freq:
  value: 4
