wandb_version: 1

a_bits_per_feature:
  value: 6
a_nr_of_clauses:
  value: 960
a_number_of_state_bits_ta:
  value: 5
a_specificity:
  value: 2.5500000000000016
a_t:
  value: 0.38
c_bits_per_feature:
  value: 14
c_nr_of_clauses:
  value: 1700
c_number_of_state_bits_ta:
  value: 6
c_specificity:
  value: 7.7800000000000065
c_t:
  value: 0.24
c_y_max:
  value: 70
c_y_min:
  value: 20
gamma:
  value: 0.994
update_freq:
  value: 5
