wandb_version: 1

a_bits_per_feature:
  value: 9
a_nr_of_clauses:
  value: 900
a_number_of_state_bits_ta:
  value: 3
a_specificity:
  value: 8.770000000000007
a_t:
  value: 0.8400000000000001
c_bits_per_feature:
  value: 9
c_nr_of_clauses:
  value: 1950
c_number_of_state_bits_ta:
  value: 8
c_specificity:
  value: 5.5400000000000045
c_t:
  value: 0.87
c_y_max:
  value: 60
c_y_min:
  value: 25
gamma:
  value: 0.972
update_freq:
  value: 5
