wandb_version: 1

a_bits_per_feature:
  value: 8
a_nr_of_clauses:
  value: 1100
a_number_of_state_bits_ta:
  value: 4
a_specificity:
  value: 5.640000000000004
a_t:
  value: 0.16
c_bits_per_feature:
  value: 8
c_nr_of_clauses:
  value: 1550
c_number_of_state_bits_ta:
  value: 3
c_specificity:
  value: 1.2000000000000002
c_t:
  value: 0.86
c_y_max:
  value: 70
c_y_min:
  value: 35
gamma:
  value: 0.984
update_freq:
  value: 7
