wandb_version: 1

a_bits_per_feature:
  value: 8
a_nr_of_clauses:
  value: 1160
a_number_of_state_bits_ta:
  value: 9
a_specificity:
  value: 7.410000000000005
a_t:
  value: 0.22
c_bits_per_feature:
  value: 11
c_nr_of_clauses:
  value: 1000
c_number_of_state_bits_ta:
  value: 3
c_specificity:
  value: 2.410000000000001
c_t:
  value: 0.73
c_y_max:
  value: 75
c_y_min:
  value: 20
gamma:
  value: 0.959
update_freq:
  value: 3
