wandb_version: 1

a_bits_per_feature:
  value: 10
a_nr_of_clauses:
  value: 1120
a_number_of_state_bits_ta:
  value: 3
a_specificity:
  value: 9.350000000000009
a_t:
  value: 0.6900000000000001
c_bits_per_feature:
  value: 6
c_nr_of_clauses:
  value: 1700
c_number_of_state_bits_ta:
  value: 8
c_specificity:
  value: 1.4200000000000004
c_t:
  value: 0.8
c_y_max:
  value: 70
c_y_min:
  value: 20
gamma:
  value: 0.993
update_freq:
  value: 5
