wandb_version: 1

a_bits_per_feature:
  value: 5
a_nr_of_clauses:
  value: 940
a_number_of_state_bits_ta:
  value: 7
a_specificity:
  value: 1.6100000000000003
a_t:
  value: 0.28
c_bits_per_feature:
  value: 8
c_nr_of_clauses:
  value: 900
c_number_of_state_bits_ta:
  value: 5
c_specificity:
  value: 4.430000000000003
c_t:
  value: 0.24
c_y_max:
  value: 60
c_y_min:
  value: 25
gamma:
  value: 0.996
update_freq:
  value: 5
