wandb_version: 1

a_bits_per_feature:
  value: 7
a_nr_of_clauses:
  value: 1040
a_number_of_state_bits_ta:
  value: 7
a_specificity:
  value: 6.810000000000005
a_t:
  value: 0.32
c_bits_per_feature:
  value: 8
c_nr_of_clauses:
  value: 1600
c_number_of_state_bits_ta:
  value: 3
c_specificity:
  value: 8.900000000000007
c_t:
  value: 0.19
c_y_max:
  value: 70
c_y_min:
  value: 30
gamma:
  value: 0.939
update_freq:
  value: 5
