wandb_version: 1

a_bits_per_feature:
  value: 10
a_nr_of_clauses:
  value: 1000
a_number_of_state_bits_ta:
  value: 7
a_specificity:
  value: 3.290000000000002
a_t:
  value: 0.24
c_bits_per_feature:
  value: 13
c_nr_of_clauses:
  value: 1300
c_number_of_state_bits_ta:
  value: 4
c_specificity:
  value: 9.450000000000008
c_t:
  value: 0.27
c_y_max:
  value: 60
c_y_min:
  value: 30
gamma:
  value: 0.943
update_freq:
  value: 4
