wandb_version: 1

a_bits_per_feature:
  value: 11
a_nr_of_clauses:
  value: 900
a_number_of_state_bits_ta:
  value: 9
a_specificity:
  value: 8.730000000000008
a_t:
  value: 0.6900000000000001
c_bits_per_feature:
  value: 6
c_nr_of_clauses:
  value: 1950
c_number_of_state_bits_ta:
  value: 4
c_specificity:
  value: 7.150000000000006
c_t:
  value: 0.66
c_y_max:
  value: 75
c_y_min:
  value: 35
gamma:
  value: 0.96
update_freq:
  value: 6
