wandb_version: 1

a_bits_per_feature:
  value: 13
a_nr_of_clauses:
  value: 1080
a_number_of_state_bits_ta:
  value: 7
a_specificity:
  value: 8.800000000000008
a_t:
  value: 0.77
c_bits_per_feature:
  value: 10
c_nr_of_clauses:
  value: 1150
c_number_of_state_bits_ta:
  value: 8
c_specificity:
  value: 7.810000000000006
c_t:
  value: 0.7000000000000001
c_y_max:
  value: 60
c_y_min:
  value: 25
gamma:
  value: 0.989
update_freq:
  value: 3
