wandb_version: 1

a_bits_per_feature:
  value: 13
a_nr_of_clauses:
  value: 1100
a_number_of_state_bits_ta:
  value: 9
a_specificity:
  value: 8.230000000000008
a_t:
  value: 0.23
c_bits_per_feature:
  value: 8
c_nr_of_clauses:
  value: 1300
c_number_of_state_bits_ta:
  value: 6
c_specificity:
  value: 2.6600000000000015
c_t:
  value: 0.65
c_y_max:
  value: 65
c_y_min:
  value: 20
gamma:
  value: 0.931
update_freq:
  value: 3
