wandb_version: 1

a_bits_per_feature:
  value: 10
a_nr_of_clauses:
  value: 980
a_number_of_state_bits_ta:
  value: 7
a_specificity:
  value: 7.120000000000005
a_t:
  value: 0.55
c_bits_per_feature:
  value: 13
c_nr_of_clauses:
  value: 800
c_number_of_state_bits_ta:
  value: 3
c_specificity:
  value: 8.800000000000008
c_t:
  value: 0.49
c_y_max:
  value: 75
c_y_min:
  value: 35
gamma:
  value: 0.913
update_freq:
  value: 4
