wandb_version: 1

a_bits_per_feature:
  value: 11
a_nr_of_clauses:
  value: 840
a_number_of_state_bits_ta:
  value: 8
a_specificity:
  value: 2.540000000000002
a_t:
  value: 0.9
c_bits_per_feature:
  value: 10
c_nr_of_clauses:
  value: 1950
c_number_of_state_bits_ta:
  value: 7
c_specificity:
  value: 5.080000000000004
c_t:
  value: 0.59
c_y_max:
  value: 75
c_y_min:
  value: 30
gamma:
  value: 0.993
update_freq:
  value: 4
