wandb_version: 1

a_bits_per_feature:
  value: 10
a_nr_of_clauses:
  value: 840
a_number_of_state_bits_ta:
  value: 6
a_specificity:
  value: 8.400000000000006
a_t:
  value: 0.16
c_bits_per_feature:
  value: 10
c_nr_of_clauses:
  value: 1300
c_number_of_state_bits_ta:
  value: 5
c_specificity:
  value: 4.410000000000003
c_t:
  value: 0.11
c_y_max:
  value: 75
c_y_min:
  value: 30
gamma:
  value: 0.964
update_freq:
  value: 3
