wandb_version: 1

a_bits_per_feature:
  value: 12
a_nr_of_clauses:
  value: 960
a_number_of_state_bits_ta:
  value: 6
a_specificity:
  value: 5.860000000000005
a_t:
  value: 0.11
c_bits_per_feature:
  value: 7
c_nr_of_clauses:
  value: 1550
c_number_of_state_bits_ta:
  value: 3
c_specificity:
  value: 2.320000000000001
c_t:
  value: 0.05
c_y_max:
  value: 75
c_y_min:
  value: 25
gamma:
  value: 0.971
update_freq:
  value: 4
