wandb_version: 1

a_bits_per_feature:
  value: 9
a_nr_of_clauses:
  value: 940
a_number_of_state_bits_ta:
  value: 7
a_specificity:
  value: 4.180000000000003
a_t:
  value: 0.09
c_bits_per_feature:
  value: 10
c_nr_of_clauses:
  value: 1500
c_number_of_state_bits_ta:
  value: 7
c_specificity:
  value: 7.700000000000006
c_t:
  value: 0.27
c_y_max:
  value: 60
c_y_min:
  value: 25
gamma:
  value: 0.94
update_freq:
  value: 6
