wandb_version: 1

a_bits_per_feature:
  value: 14
a_nr_of_clauses:
  value: 1140
a_number_of_state_bits_ta:
  value: 5
a_specificity:
  value: 2.4400000000000013
a_t:
  value: 0.9
c_bits_per_feature:
  value: 10
c_nr_of_clauses:
  value: 950
c_number_of_state_bits_ta:
  value: 6
c_specificity:
  value: 8.330000000000005
c_t:
  value: 0.75
c_y_max:
  value: 75
c_y_min:
  value: 35
gamma:
  value: 0.992
update_freq:
  value: 7
