wandb_version: 1

a_bits_per_feature:
  value: 5
a_nr_of_clauses:
  value: 800
a_number_of_state_bits_ta:
  value: 5
a_specificity:
  value: 4.320000000000003
a_t:
  value: 0.03
c_bits_per_feature:
  value: 7
c_nr_of_clauses:
  value: 1200
c_number_of_state_bits_ta:
  value: 4
c_specificity:
  value: 6.300000000000004
c_t:
  value: 0.42
c_y_max:
  value: 65
c_y_min:
  value: 35
gamma:
  value: 0.946
update_freq:
  value: 4
