wandb_version: 1

a_bits_per_feature:
  value: 9
a_nr_of_clauses:
  value: 880
a_number_of_state_bits_ta:
  value: 3
a_specificity:
  value: 2.5600000000000014
a_t:
  value: 0.26
c_bits_per_feature:
  value: 12
c_nr_of_clauses:
  value: 1900
c_number_of_state_bits_ta:
  value: 6
c_specificity:
  value: 8.650000000000006
c_t:
  value: 0.97
c_y_max:
  value: 60
c_y_min:
  value: 30
gamma:
  value: 0.902
update_freq:
  value: 7
