wandb_version: 1

a_bits_per_feature:
  value: 11
a_nr_of_clauses:
  value: 1000
a_number_of_state_bits_ta:
  value: 4
a_specificity:
  value: 1.5900000000000003
a_t:
  value: 0.99
c_bits_per_feature:
  value: 14
c_nr_of_clauses:
  value: 800
c_number_of_state_bits_ta:
  value: 7
c_specificity:
  value: 2.9800000000000018
c_t:
  value: 0.53
c_y_max:
  value: 60
c_y_min:
  value: 25
gamma:
  value: 0.907
update_freq:
  value: 6
