wandb_version: 1

a_bits_per_feature:
  value: 8
a_nr_of_clauses:
  value: 960
a_number_of_state_bits_ta:
  value: 8
a_specificity:
  value: 5.280000000000004
a_t:
  value: 0.7000000000000001
c_bits_per_feature:
  value: 7
c_nr_of_clauses:
  value: 1100
c_number_of_state_bits_ta:
  value: 9
c_specificity:
  value: 7.1600000000000055
c_t:
  value: 0.02
c_y_max:
  value: 60
c_y_min:
  value: 20
gamma:
  value: 0.919
update_freq:
  value: 5
