wandb_version: 1

a_bits_per_feature:
  value: 11
a_nr_of_clauses:
  value: 900
a_number_of_state_bits_ta:
  value: 9
a_specificity:
  value: 8.950000000000006
a_t:
  value: 0.28
c_bits_per_feature:
  value: 12
c_nr_of_clauses:
  value: 1000
c_number_of_state_bits_ta:
  value: 7
c_specificity:
  value: 4.910000000000004
c_t:
  value: 0.6900000000000001
c_y_max:
  value: 70
c_y_min:
  value: 30
gamma:
  value: 0.968
update_freq:
  value: 7
