wandb_version: 1

a_bits_per_feature:
  value: 12
a_nr_of_clauses:
  value: 1060
a_number_of_state_bits_ta:
  value: 4
a_specificity:
  value: 6.590000000000005
a_t:
  value: 0.4
c_bits_per_feature:
  value: 10
c_nr_of_clauses:
  value: 800
c_number_of_state_bits_ta:
  value: 5
c_specificity:
  value: 8.210000000000006
c_t:
  value: 0.45
c_y_max:
  value: 75
c_y_min:
  value: 25
gamma:
  value: 0.98
update_freq:
  value: 7
