wandb_version: 1

a_bits_per_feature:
  value: 7
a_nr_of_clauses:
  value: 900
a_number_of_state_bits_ta:
  value: 7
a_specificity:
  value: 6.420000000000005
a_t:
  value: 0.12
c_bits_per_feature:
  value: 9
c_nr_of_clauses:
  value: 1150
c_number_of_state_bits_ta:
  value: 6
c_specificity:
  value: 1.07
c_t:
  value: 0.7000000000000001
c_y_max:
  value: 65
c_y_min:
  value: 20
gamma:
  value: 0.938
update_freq:
  value: 5
