wandb_version: 1

a_bits_per_feature:
  value: 8
a_nr_of_clauses:
  value: 1040
a_number_of_state_bits_ta:
  value: 8
a_specificity:
  value: 8.740000000000007
a_t:
  value: 0.11
c_bits_per_feature:
  value: 11
c_nr_of_clauses:
  value: 1550
c_number_of_state_bits_ta:
  value: 8
c_specificity:
  value: 7.680000000000006
c_t:
  value: 0.13
c_y_max:
  value: 70
c_y_min:
  value: 30
gamma:
  value: 0.987
update_freq:
  value: 6
