wandb_version: 1

a_bits_per_feature:
  value: 11
a_nr_of_clauses:
  value: 1140
a_number_of_state_bits_ta:
  value: 3
a_specificity:
  value: 7.7800000000000065
a_t:
  value: 0.64
c_bits_per_feature:
  value: 7
c_nr_of_clauses:
  value: 1200
c_number_of_state_bits_ta:
  value: 9
c_specificity:
  value: 8.380000000000006
c_t:
  value: 0.02
c_y_max:
  value: 65
c_y_min:
  value: 35
gamma:
  value: 0.962
update_freq:
  value: 7
