wandb_version: 1

a_bits_per_feature:
  value: 10
a_nr_of_clauses:
  value: 1100
a_number_of_state_bits_ta:
  value: 8
a_specificity:
  value: 5.400000000000004
a_t:
  value: 0.97
c_bits_per_feature:
  value: 14
c_nr_of_clauses:
  value: 1650
c_number_of_state_bits_ta:
  value: 9
c_specificity:
  value: 1.6500000000000006
c_t:
  value: 0.68
c_y_max:
  value: 60
c_y_min:
  value: 20
gamma:
  value: 0.937
update_freq:
  value: 3
