wandb_version: 1

a_bits_per_feature:
  value: 13
a_nr_of_clauses:
  value: 940
a_number_of_state_bits_ta:
  value: 8
a_specificity:
  value: 8.870000000000008
a_t:
  value: 0.09
c_bits_per_feature:
  value: 8
c_nr_of_clauses:
  value: 950
c_number_of_state_bits_ta:
  value: 8
c_specificity:
  value: 4.620000000000003
c_t:
  value: 0.38
c_y_max:
  value: 75
c_y_min:
  value: 25
gamma:
  value: 0.926
update_freq:
  value: 3
