wandb_version: 1

a_bits_per_feature:
  value: 9
a_nr_of_clauses:
  value: 860
a_number_of_state_bits_ta:
  value: 4
a_specificity:
  value: 9.360000000000008
a_t:
  value: 0.75
c_bits_per_feature:
  value: 14
c_nr_of_clauses:
  value: 1250
c_number_of_state_bits_ta:
  value: 8
c_specificity:
  value: 4.650000000000003
c_t:
  value: 0.92
c_y_max:
  value: 60
c_y_min:
  value: 20
gamma:
  value: 0.963
update_freq:
  value: 4
