wandb_version: 1

a_bits_per_feature:
  value: 7
a_nr_of_clauses:
  value: 1140
a_number_of_state_bits_ta:
  value: 8
a_specificity:
  value: 7.400000000000006
a_t:
  value: 0.5800000000000001
c_bits_per_feature:
  value: 10
c_nr_of_clauses:
  value: 1700
c_number_of_state_bits_ta:
  value: 9
c_specificity:
  value: 9.940000000000008
c_t:
  value: 0.97
c_y_max:
  value: 60
c_y_min:
  value: 30
gamma:
  value: 0.924
update_freq:
  value: 3
