wandb_version: 1

a_bits_per_feature:
  value: 14
a_nr_of_clauses:
  value: 1000
a_number_of_state_bits_ta:
  value: 3
a_specificity:
  value: 1.5800000000000003
a_t:
  value: 0.29000000000000004
c_bits_per_feature:
  value: 10
c_nr_of_clauses:
  value: 1400
c_number_of_state_bits_ta:
  value: 4
c_specificity:
  value: 1.7800000000000007
c_t:
  value: 0.66
c_y_max:
  value: 65
c_y_min:
  value: 35
gamma:
  value: 0.993
update_freq:
  value: 7
