wandb_version: 1

a_bits_per_feature:
  value: 12
a_nr_of_clauses:
  value: 940
a_number_of_state_bits_ta:
  value: 8
a_specificity:
  value: 7.680000000000006
a_t:
  value: 0.67
c_bits_per_feature:
  value: 6
c_nr_of_clauses:
  value: 1450
c_number_of_state_bits_ta:
  value: 8
c_specificity:
  value: 8.940000000000007
c_t:
  value: 0.05
c_y_max:
  value: 70
c_y_min:
  value: 35
gamma:
  value: 0.916
update_freq:
  value: 3
