wandb_version: 1

a_bits_per_feature:
  value: 10
a_nr_of_clauses:
  value: 1180
a_number_of_state_bits_ta:
  value: 9
a_specificity:
  value: 2.9800000000000018
a_t:
  value: 0.12
c_bits_per_feature:
  value: 10
c_nr_of_clauses:
  value: 1450
c_number_of_state_bits_ta:
  value: 7
c_specificity:
  value: 7.250000000000005
c_t:
  value: 0.45
c_y_max:
  value: 60
c_y_min:
  value: 35
gamma:
  value: 0.962
update_freq:
  value: 4
