wandb_version: 1

a_bits_per_feature:
  value: 11
a_nr_of_clauses:
  value: 940
a_number_of_state_bits_ta:
  value: 3
a_specificity:
  value: 1.03
a_t:
  value: 0.54
c_bits_per_feature:
  value: 8
c_nr_of_clauses:
  value: 1300
c_number_of_state_bits_ta:
  value: 8
c_specificity:
  value: 2.000000000000001
c_t:
  value: 0.86
c_y_max:
  value: 60
c_y_min:
  value: 25
gamma:
  value: 0.951
update_freq:
  value: 7
