wandb_version: 1

a_bits_per_feature:
  value: 11
a_nr_of_clauses:
  value: 1180
a_number_of_state_bits_ta:
  value: 5
a_specificity:
  value: 2.0500000000000007
a_t:
  value: 0.35000000000000003
c_bits_per_feature:
  value: 5
c_nr_of_clauses:
  value: 1600
c_number_of_state_bits_ta:
  value: 9
c_specificity:
  value: 8.200000000000006
c_t:
  value: 0.5700000000000001
c_y_max:
  value: 65
c_y_min:
  value: 25
gamma:
  value: 0.909
update_freq:
  value: 4
