wandb_version: 1

a_bits_per_feature:
  value: 14
a_nr_of_clauses:
  value: 1140
a_number_of_state_bits_ta:
  value: 5
a_specificity:
  value: 6.090000000000004
a_t:
  value: 0.34
c_bits_per_feature:
  value: 13
c_nr_of_clauses:
  value: 950
c_number_of_state_bits_ta:
  value: 9
c_specificity:
  value: 7.090000000000005
c_t:
  value: 0.8
c_y_max:
  value: 75
c_y_min:
  value: 35
gamma:
  value: 0.906
update_freq:
  value: 6
