wandb_version: 1

a_bits_per_feature:
  value: 9
a_nr_of_clauses:
  value: 1180
a_number_of_state_bits_ta:
  value: 9
a_specificity:
  value: 8.740000000000007
a_t:
  value: 0.72
c_bits_per_feature:
  value: 8
c_nr_of_clauses:
  value: 1450
c_number_of_state_bits_ta:
  value: 8
c_specificity:
  value: 8.040000000000006
c_t:
  value: 0.01
c_y_max:
  value: 70
c_y_min:
  value: 35
gamma:
  value: 0.969
update_freq:
  value: 3
