wandb_version: 1

a_bits_per_feature:
  value: 10
a_nr_of_clauses:
  value: 920
a_number_of_state_bits_ta:
  value: 5
a_specificity:
  value: 9.520000000000008
a_t:
  value: 0.96
c_bits_per_feature:
  value: 6
c_nr_of_clauses:
  value: 1050
c_number_of_state_bits_ta:
  value: 7
c_specificity:
  value: 3.9700000000000024
c_t:
  value: 0.81
c_y_max:
  value: 70
c_y_min:
  value: 20
gamma:
  value: 0.949
update_freq:
  value: 7
