wandb_version: 1

a_bits_per_feature:
  value: 10
a_nr_of_clauses:
  value: 980
a_number_of_state_bits_ta:
  value: 5
a_specificity:
  value: 6.160000000000005
a_t:
  value: 0.55
c_bits_per_feature:
  value: 10
c_nr_of_clauses:
  value: 1600
c_number_of_state_bits_ta:
  value: 6
c_specificity:
  value: 8.220000000000006
c_t:
  value: 0.11
c_y_max:
  value: 65
c_y_min:
  value: 35
gamma:
  value: 0.918
update_freq:
  value: 5
