wandb_version: 1

a_bits_per_feature:
  value: 14
a_nr_of_clauses:
  value: 840
a_number_of_state_bits_ta:
  value: 9
a_specificity:
  value: 3.3900000000000023
a_t:
  value: 0.060000000000000005
c_bits_per_feature:
  value: 8
c_nr_of_clauses:
  value: 1500
c_number_of_state_bits_ta:
  value: 9
c_specificity:
  value: 8.360000000000007
c_t:
  value: 0.7000000000000001
c_y_max:
  value: 75
c_y_min:
  value: 25
gamma:
  value: 0.958
update_freq:
  value: 5
