wandb_version: 1

a_bits_per_feature:
  value: 5
a_nr_of_clauses:
  value: 1020
a_number_of_state_bits_ta:
  value: 7
a_specificity:
  value: 2.7000000000000015
a_t:
  value: 0.060000000000000005
c_bits_per_feature:
  value: 10
c_nr_of_clauses:
  value: 800
c_number_of_state_bits_ta:
  value: 6
c_specificity:
  value: 8.790000000000006
c_t:
  value: 0.02
c_y_max:
  value: 60
c_y_min:
  value: 20
gamma:
  value: 0.981
update_freq:
  value: 6
