wandb_version: 1

a_bits_per_feature:
  value: 5
a_nr_of_clauses:
  value: 880
a_number_of_state_bits_ta:
  value: 4
a_specificity:
  value: 4.680000000000003
a_t:
  value: 0.85
c_bits_per_feature:
  value: 13
c_nr_of_clauses:
  value: 1850
c_number_of_state_bits_ta:
  value: 8
c_specificity:
  value: 5.600000000000004
c_t:
  value: 0.81
c_y_max:
  value: 70
c_y_min:
  value: 25
gamma:
  value: 0.911
update_freq:
  value: 6
