wandb_version: 1

a_bits_per_feature:
  value: 9
a_nr_of_clauses:
  value: 980
a_number_of_state_bits_ta:
  value: 6
a_specificity:
  value: 2.8800000000000017
a_t:
  value: 0.8200000000000001
c_bits_per_feature:
  value: 5
c_nr_of_clauses:
  value: 1500
c_number_of_state_bits_ta:
  value: 6
c_specificity:
  value: 8.130000000000006
c_t:
  value: 0.47
c_y_max:
  value: 75
c_y_min:
  value: 30
gamma:
  value: 0.926
update_freq:
  value: 4
