wandb_version: 1

a_bits_per_feature:
  value: 13
a_nr_of_clauses:
  value: 1080
a_number_of_state_bits_ta:
  value: 4
a_specificity:
  value: 1.9600000000000009
a_t:
  value: 0.66
c_bits_per_feature:
  value: 6
c_nr_of_clauses:
  value: 1050
c_number_of_state_bits_ta:
  value: 8
c_specificity:
  value: 7.790000000000006
c_t:
  value: 0.12
c_y_max:
  value: 65
c_y_min:
  value: 25
gamma:
  value: 0.937
update_freq:
  value: 3
