wandb_version: 1

a_bits_per_feature:
  value: 5
a_nr_of_clauses:
  value: 840
a_number_of_state_bits_ta:
  value: 9
a_specificity:
  value: 7.410000000000005
a_t:
  value: 0.45
c_bits_per_feature:
  value: 14
c_nr_of_clauses:
  value: 1900
c_number_of_state_bits_ta:
  value: 4
c_specificity:
  value: 8.040000000000006
c_t:
  value: 0.43
c_y_max:
  value: 60
c_y_min:
  value: 35
gamma:
  value: 0.997
update_freq:
  value: 3
