wandb_version: 1

a_bits_per_feature:
  value: 5
a_nr_of_clauses:
  value: 1160
a_number_of_state_bits_ta:
  value: 9
a_specificity:
  value: 9.740000000000007
a_t:
  value: 0.46
c_bits_per_feature:
  value: 11
c_nr_of_clauses:
  value: 900
c_number_of_state_bits_ta:
  value: 9
c_specificity:
  value: 2.6900000000000013
c_t:
  value: 0.1
c_y_max:
  value: 60
c_y_min:
  value: 25
gamma:
  value: 0.956
update_freq:
  value: 4
