wandb_version: 1

a_bits_per_feature:
  value: 14
a_nr_of_clauses:
  value: 1040
a_number_of_state_bits_ta:
  value: 4
a_specificity:
  value: 6.430000000000005
a_t:
  value: 0.91
c_bits_per_feature:
  value: 11
c_nr_of_clauses:
  value: 1100
c_number_of_state_bits_ta:
  value: 5
c_specificity:
  value: 4.810000000000003
c_t:
  value: 0.31
c_y_max:
  value: 70
c_y_min:
  value: 20
gamma:
  value: 0.996
update_freq:
  value: 6
