wandb_version: 1

a_bits_per_feature:
  value: 14
a_nr_of_clauses:
  value: 1000
a_number_of_state_bits_ta:
  value: 5
a_specificity:
  value: 5.860000000000005
a_t:
  value: 0.3
c_bits_per_feature:
  value: 9
c_nr_of_clauses:
  value: 800
c_number_of_state_bits_ta:
  value: 5
c_specificity:
  value: 7.7800000000000065
c_t:
  value: 0.79
c_y_max:
  value: 70
c_y_min:
  value: 20
gamma:
  value: 0.902
update_freq:
  value: 6
