wandb_version: 1

a_bits_per_feature:
  value: 11
a_nr_of_clauses:
  value: 860
a_number_of_state_bits_ta:
  value: 9
a_specificity:
  value: 9.330000000000007
a_t:
  value: 0.03
c_bits_per_feature:
  value: 11
c_nr_of_clauses:
  value: 1600
c_number_of_state_bits_ta:
  value: 9
c_specificity:
  value: 9.030000000000006
c_t:
  value: 0.68
c_y_max:
  value: 60
c_y_min:
  value: 20
gamma:
  value: 0.905
update_freq:
  value: 7
