wandb_version: 1

a_bits_per_feature:
  value: 11
a_nr_of_clauses:
  value: 800
a_number_of_state_bits_ta:
  value: 8
a_specificity:
  value: 9.950000000000008
a_t:
  value: 0.29000000000000004
c_bits_per_feature:
  value: 14
c_nr_of_clauses:
  value: 1000
c_number_of_state_bits_ta:
  value: 8
c_specificity:
  value: 1.6200000000000006
c_t:
  value: 0.5700000000000001
c_y_max:
  value: 70
c_y_min:
  value: 25
gamma:
  value: 0.903
update_freq:
  value: 3
