wandb_version: 1

a_bits_per_feature:
  value: 13
a_nr_of_clauses:
  value: 820
a_number_of_state_bits_ta:
  value: 4
a_specificity:
  value: 5.140000000000004
a_t:
  value: 0.03
c_bits_per_feature:
  value: 8
c_nr_of_clauses:
  value: 1200
c_number_of_state_bits_ta:
  value: 3
c_specificity:
  value: 9.220000000000008
c_t:
  value: 0.01
c_y_max:
  value: 70
c_y_min:
  value: 25
gamma:
  value: 0.945
update_freq:
  value: 5
