wandb_version: 1

a_bits_per_feature:
  value: 14
a_nr_of_clauses:
  value: 1160
a_number_of_state_bits_ta:
  value: 8
a_specificity:
  value: 6.2900000000000045
a_t:
  value: 0.46
c_bits_per_feature:
  value: 12
c_nr_of_clauses:
  value: 1500
c_number_of_state_bits_ta:
  value: 4
c_specificity:
  value: 1.5400000000000005
c_t:
  value: 0.7000000000000001
c_y_max:
  value: 60
c_y_min:
  value: 20
gamma:
  value: 0.959
update_freq:
  value: 7
