wandb_version: 1

a_bits_per_feature:
  value: 8
a_nr_of_clauses:
  value: 1160
a_number_of_state_bits_ta:
  value: 6
a_specificity:
  value: 7.700000000000006
a_t:
  value: 0.93
c_bits_per_feature:
  value: 6
c_nr_of_clauses:
  value: 800
c_number_of_state_bits_ta:
  value: 6
c_specificity:
  value: 5.650000000000004
c_t:
  value: 0.54
c_y_max:
  value: 75
c_y_min:
  value: 35
gamma:
  value: 0.974
update_freq:
  value: 7
