wandb_version: 1

a_bits_per_feature:
  value: 11
a_nr_of_clauses:
  value: 1120
a_number_of_state_bits_ta:
  value: 3
a_specificity:
  value: 8.360000000000007
a_t:
  value: 0.99
c_bits_per_feature:
  value: 7
c_nr_of_clauses:
  value: 1600
c_number_of_state_bits_ta:
  value: 6
c_specificity:
  value: 4.060000000000002
c_t:
  value: 0.87
c_y_max:
  value: 70
c_y_min:
  value: 25
gamma:
  value: 0.907
update_freq:
  value: 6
