wandb_version: 1

a_bits_per_feature:
  value: 6
a_nr_of_clauses:
  value: 1000
a_number_of_state_bits_ta:
  value: 8
a_specificity:
  value: 4.510000000000003
a_t:
  value: 0.99
c_bits_per_feature:
  value: 12
c_nr_of_clauses:
  value: 1650
c_number_of_state_bits_ta:
  value: 4
c_specificity:
  value: 1.8500000000000008
c_t:
  value: 0.72
c_y_max:
  value: 60
c_y_min:
  value: 35
gamma:
  value: 0.958
update_freq:
  value: 5
