wandb_version: 1

a_bits_per_feature:
  value: 13
a_nr_of_clauses:
  value: 860
a_number_of_state_bits_ta:
  value: 3
a_specificity:
  value: 7.290000000000005
a_t:
  value: 0.73
c_bits_per_feature:
  value: 6
c_nr_of_clauses:
  value: 1000
c_number_of_state_bits_ta:
  value: 5
c_specificity:
  value: 6.810000000000005
c_t:
  value: 0.6900000000000001
c_y_max:
  value: 65
c_y_min:
  value: 30
gamma:
  value: 0.953
update_freq:
  value: 4
