wandb_version: 1

a_bits_per_feature:
  value: 5
a_nr_of_clauses:
  value: 900
a_number_of_state_bits_ta:
  value: 9
a_specificity:
  value: 8.980000000000008
a_t:
  value: 0.85
c_bits_per_feature:
  value: 9
c_nr_of_clauses:
  value: 1450
c_number_of_state_bits_ta:
  value: 4
c_specificity:
  value: 9.760000000000009
c_t:
  value: 0.88
c_y_max:
  value: 70
c_y_min:
  value: 20
gamma:
  value: 0.984
update_freq:
  value: 7
