wandb_version: 1

a_bits_per_feature:
  value: 9
a_nr_of_clauses:
  value: 1000
a_number_of_state_bits_ta:
  value: 4
a_specificity:
  value: 8.010000000000005
a_t:
  value: 0.78
c_bits_per_feature:
  value: 11
c_nr_of_clauses:
  value: 1400
c_number_of_state_bits_ta:
  value: 3
c_specificity:
  value: 4.940000000000003
c_t:
  value: 0.87
c_y_max:
  value: 60
c_y_min:
  value: 30
gamma:
  value: 0.903
update_freq:
  value: 3
