wandb_version: 1

a_bits_per_feature:
  value: 10
a_nr_of_clauses:
  value: 1140
a_number_of_state_bits_ta:
  value: 5
a_specificity:
  value: 5.080000000000004
a_t:
  value: 0.12
c_bits_per_feature:
  value: 10
c_nr_of_clauses:
  value: 1050
c_number_of_state_bits_ta:
  value: 7
c_specificity:
  value: 2.0900000000000007
c_t:
  value: 0.03
c_y_max:
  value: 70
c_y_min:
  value: 25
gamma:
  value: 0.964
update_freq:
  value: 3
