wandb_version: 1

a_bits_per_feature:
  value: 11
a_nr_of_clauses:
  value: 860
a_number_of_state_bits_ta:
  value: 3
a_specificity:
  value: 4.580000000000004
a_t:
  value: 0.26
c_bits_per_feature:
  value: 10
c_nr_of_clauses:
  value: 1650
c_number_of_state_bits_ta:
  value: 7
c_specificity:
  value: 1.8700000000000008
c_t:
  value: 0.48
c_y_max:
  value: 75
c_y_min:
  value: 30
gamma:
  value: 0.902
update_freq:
  value: 5
