wandb_version: 1

a_bits_per_feature:
  value: 9
a_nr_of_clauses:
  value: 840
a_number_of_state_bits_ta:
  value: 4
a_specificity:
  value: 9.760000000000009
a_t:
  value: 0.4
c_bits_per_feature:
  value: 9
c_nr_of_clauses:
  value: 1100
c_number_of_state_bits_ta:
  value: 4
c_specificity:
  value: 2.8100000000000014
c_t:
  value: 0.08
c_y_max:
  value: 65
c_y_min:
  value: 30
gamma:
  value: 0.99
update_freq:
  value: 4
