wandb_version: 1

a_bits_per_feature:
  value: 10
a_nr_of_clauses:
  value: 960
a_number_of_state_bits_ta:
  value: 8
a_specificity:
  value: 5.470000000000004
a_t:
  value: 0.47
c_bits_per_feature:
  value: 6
c_nr_of_clauses:
  value: 1300
c_number_of_state_bits_ta:
  value: 8
c_specificity:
  value: 4.380000000000003
c_t:
  value: 0.16
c_y_max:
  value: 75
c_y_min:
  value: 35
gamma:
  value: 0.991
update_freq:
  value: 3
