wandb_version: 1

a_bits_per_feature:
  value: 11
a_nr_of_clauses:
  value: 980
a_number_of_state_bits_ta:
  value: 9
a_specificity:
  value: 8.260000000000007
a_t:
  value: 0.91
c_bits_per_feature:
  value: 9
c_nr_of_clauses:
  value: 1450
c_number_of_state_bits_ta:
  value: 7
c_specificity:
  value: 1.9200000000000008
c_t:
  value: 0.64
c_y_max:
  value: 75
c_y_min:
  value: 35
gamma:
  value: 0.9
update_freq:
  value: 7
