wandb_version: 1

a_bits_per_feature:
  value: 10
a_nr_of_clauses:
  value: 1000
a_number_of_state_bits_ta:
  value: 6
a_specificity:
  value: 6.500000000000005
a_t:
  value: 0.59
c_bits_per_feature:
  value: 6
c_nr_of_clauses:
  value: 1200
c_number_of_state_bits_ta:
  value: 5
c_specificity:
  value: 7.400000000000006
c_t:
  value: 0.32
c_y_max:
  value: 60
c_y_min:
  value: 25
gamma:
  value: 0.93
update_freq:
  value: 4
