wandb_version: 1

a_bits_per_feature:
  value: 9
a_nr_of_clauses:
  value: 820
a_number_of_state_bits_ta:
  value: 4
a_specificity:
  value: 4.7100000000000035
a_t:
  value: 0.75
c_bits_per_feature:
  value: 12
c_nr_of_clauses:
  value: 1600
c_number_of_state_bits_ta:
  value: 8
c_specificity:
  value: 6.170000000000004
c_t:
  value: 0.7000000000000001
c_y_max:
  value: 60
c_y_min:
  value: 20
gamma:
  value: 0.973
update_freq:
  value: 6
