wandb_version: 1

a_bits_per_feature:
  value: 10
a_nr_of_clauses:
  value: 820
a_number_of_state_bits_ta:
  value: 7
a_specificity:
  value: 2.4400000000000013
a_t:
  value: 0.14
c_bits_per_feature:
  value: 14
c_nr_of_clauses:
  value: 1850
c_number_of_state_bits_ta:
  value: 8
c_specificity:
  value: 8.260000000000007
c_t:
  value: 0.16
c_y_max:
  value: 65
c_y_min:
  value: 20
gamma:
  value: 0.929
update_freq:
  value: 7
