wandb_version: 1

a_bits_per_feature:
  value: 8
a_nr_of_clauses:
  value: 1040
a_number_of_state_bits_ta:
  value: 7
a_specificity:
  value: 8.090000000000007
a_t:
  value: 0.86
c_bits_per_feature:
  value: 11
c_nr_of_clauses:
  value: 1300
c_number_of_state_bits_ta:
  value: 5
c_specificity:
  value: 2.490000000000001
c_t:
  value: 0.17
c_y_max:
  value: 75
c_y_min:
  value: 35
gamma:
  value: 0.929
update_freq:
  value: 6
