wandb_version: 1

a_bits_per_feature:
  value: 6
a_nr_of_clauses:
  value: 1180
a_number_of_state_bits_ta:
  value: 7
a_specificity:
  value: 2.610000000000001
a_t:
  value: 0.3
c_bits_per_feature:
  value: 8
c_nr_of_clauses:
  value: 1250
c_number_of_state_bits_ta:
  value: 6
c_specificity:
  value: 7.770000000000006
c_t:
  value: 0.34
c_y_max:
  value: 60
c_y_min:
  value: 20
gamma:
  value: 0.961
update_freq:
  value: 6
