wandb_version: 1

a_bits_per_feature:
  value: 8
a_nr_of_clauses:
  value: 980
a_number_of_state_bits_ta:
  value: 6
a_specificity:
  value: 2.9400000000000017
a_t:
  value: 0.39
c_bits_per_feature:
  value: 8
c_nr_of_clauses:
  value: 1200
c_number_of_state_bits_ta:
  value: 9
c_specificity:
  value: 5.530000000000004
c_t:
  value: 0.56
c_y_max:
  value: 65
c_y_min:
  value: 20
gamma:
  value: 0.964
update_freq:
  value: 4
