wandb_version: 1

a_bits_per_feature:
  value: 6
a_nr_of_clauses:
  value: 940
a_number_of_state_bits_ta:
  value: 7
a_specificity:
  value: 3.1700000000000017
a_t:
  value: 0.8
c_bits_per_feature:
  value: 8
c_nr_of_clauses:
  value: 1050
c_number_of_state_bits_ta:
  value: 9
c_specificity:
  value: 2.910000000000002
c_t:
  value: 0.06999999999999999
c_y_max:
  value: 70
c_y_min:
  value: 35
gamma:
  value: 0.921
update_freq:
  value: 4
