wandb_version: 1

a_bits_per_feature:
  value: 12
a_nr_of_clauses:
  value: 880
a_number_of_state_bits_ta:
  value: 9
a_specificity:
  value: 3.180000000000002
a_t:
  value: 0.3
c_bits_per_feature:
  value: 13
c_nr_of_clauses:
  value: 1550
c_number_of_state_bits_ta:
  value: 6
c_specificity:
  value: 1.3600000000000003
c_t:
  value: 0.060000000000000005
c_y_max:
  value: 60
c_y_min:
  value: 30
gamma:
  value: 0.969
update_freq:
  value: 5
