wandb_version: 1

a_bits_per_feature:
  value: 6
a_nr_of_clauses:
  value: 920
a_number_of_state_bits_ta:
  value: 5
a_specificity:
  value: 2.5900000000000016
a_t:
  value: 0.2
c_bits_per_feature:
  value: 5
c_nr_of_clauses:
  value: 800
c_number_of_state_bits_ta:
  value: 7
c_specificity:
  value: 9.090000000000009
c_t:
  value: 0.14
c_y_max:
  value: 60
c_y_min:
  value: 25
gamma:
  value: 0.992
update_freq:
  value: 6
