wandb_version: 1

a_bits_per_feature:
  value: 8
a_nr_of_clauses:
  value: 960
a_number_of_state_bits_ta:
  value: 7
a_specificity:
  value: 8.570000000000007
a_t:
  value: 0.19
c_bits_per_feature:
  value: 5
c_nr_of_clauses:
  value: 1600
c_number_of_state_bits_ta:
  value: 8
c_specificity:
  value: 1.9300000000000008
c_t:
  value: 0.53
c_y_max:
  value: 60
c_y_min:
  value: 30
gamma:
  value: 0.915
update_freq:
  value: 4
