wandb_version: 1

a_bits_per_feature:
  value: 9
a_nr_of_clauses:
  value: 800
a_number_of_state_bits_ta:
  value: 6
a_specificity:
  value: 7.270000000000006
a_t:
  value: 0.31
c_bits_per_feature:
  value: 5
c_nr_of_clauses:
  value: 1300
c_number_of_state_bits_ta:
  value: 6
c_specificity:
  value: 5.810000000000004
c_t:
  value: 0.78
c_y_max:
  value: 65
c_y_min:
  value: 25
gamma:
  value: 0.938
update_freq:
  value: 4
