wandb_version: 1

a_bits_per_feature:
  value: 6
a_nr_of_clauses:
  value: 820
a_number_of_state_bits_ta:
  value: 4
a_specificity:
  value: 1.8300000000000007
a_t:
  value: 0.89
c_bits_per_feature:
  value: 9
c_nr_of_clauses:
  value: 1500
c_number_of_state_bits_ta:
  value: 3
c_specificity:
  value: 5.190000000000004
c_t:
  value: 0.3
c_y_max:
  value: 70
c_y_min:
  value: 20
gamma:
  value: 0.932
update_freq:
  value: 5
