action_space_size: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  AwAAAAAAAAA=
actor:
  T: 1368
  bits_per_feature: 9
  device: CPU
  nr_of_clauses: 1800
  number_of_state_bits_ta: 5
  s: 7.660000000000005
  seed: 42
  weighted_clauses: false
algorithm: TAC_a
batch_size: 32
buffer_size: 8000
critic:
  T: 1037
  bits_per_feature: 14
  device: CPU
  max_update_p: 0.026
  nr_of_clauses: 1700
  number_of_state_bits_ta: 7
  s: 3.8100000000000023
  seed: 42
  weighted_clauses: false
  y_max: -5
  y_min: -60
dataset_file_name: acrobot_obs_data
env_name: acrobot
epochs: 5
exploration_prob_decay: 0.009000000000000001
exploration_prob_init: 0.5
gamma: 0.926
obs_space_size: 6
save: true
soft_update_type: soft_update_1
test_freq: 1
threshold: -495
update_grad: 0.258
