action_space_size: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  AwAAAAAAAAA=
actor:
  T: 1274
  bits_per_feature: 11
  device: CPU
  nr_of_clauses: 1300
  number_of_state_bits_ta: 8
  s: 8.680000000000007
  seed: 42
  weighted_clauses: false
algorithm: TAC_b
batch_size: 32
buffer_size: 2500
critic:
  T: 152
  bits_per_feature: 12
  device: CPU
  max_update_p: 0.033
  nr_of_clauses: 1900
  number_of_state_bits_ta: 3
  s: 1.5700000000000005
  seed: 42
  weighted_clauses: false
  y_max: -5
  y_min: -65
dataset_file_name: acrobot_obs_data
env_name: acrobot
epochs: 4
exploration_prob_decay: 0.006
exploration_prob_init: 0.7999999999999999
gamma: 0.94
obs_space_size: 6
save: true
soft_update_type: soft_update_2
test_freq: 1
threshold: -495
update_freq: 8
