T: 333
algorithm: n_step_TMQN
batch_size: 80
bits_per_feature: 9
buffer_size: 4000
device: CPU
dynamic_memory: false
epochs: 2
exploration_prob_decay: 0.001
exploration_prob_init: 1.0
gamma: 0.992
n_steps: 17
nr_of_clauses: 980
nr_of_episodes: 10000
nr_of_steps: 3410992
number_of_state_bits_ta: 6
s: 8.58
save: true
test_freq: 1
weighted_clauses: false
y_max: 60
y_min: 20
