wandb_version: 1

a_bits_per_feature:
  value: 13
a_nr_of_clauses:
  value: 800
a_number_of_state_bits_ta:
  value: 3
a_specificity:
  value: 1.3100000000000005
a_t:
  value: 0.7100000000000001
c_bits_per_feature:
  value: 6
c_nr_of_clauses:
  value: 1600
c_number_of_state_bits_ta:
  value: 7
c_specificity:
  value: 9.090000000000009
c_t:
  value: 0.34
c_y_max:
  value: 70
c_y_min:
  value: 30
gamma:
  value: 0.918
update_freq:
  value: 5
