actor:
  T: 603
  bits_per_feature: 7
  device: CPU
  nr_of_classes: 2
  nr_of_clauses: 1160
  number_of_state_bits_ta: 9
  s: 4.5
  seed: 42
  weighted_clauses: false
algorithm: TM_DDPG_2
batch_size: 64
critic:
  T: 621
  bits_per_feature: 7
  device: CPU
  nr_of_clauses: 1150
  number_of_state_bits_ta: 8
  s: 6.34
  seed: 42
  weighted_clauses: false
  y_max: 65
  y_min: 30
epochs: 1
exploration_prob_decay: 0.001
exploration_prob_init: 1.0
gamma: 0.906
save: true
soft_update_type: soft_update_2
test_freq: 1
update_freq: 6
