action_space_size: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  AwAAAAAAAAA=
actor:
  T: 818
  bits_per_feature: 7
  device: CPU
  nr_of_clauses: 1860
  number_of_state_bits_ta: 3
  s: 2.98
  seed: 42
  weighted_clauses: false
algorithm: TAC_a
batch_size: 16
buffer_size: 5500
critic:
  T: 1039
  bits_per_feature: 11
  device: CPU
  max_update_p: 0.07
  nr_of_clauses: 1650
  number_of_state_bits_ta: 5
  s: 8.37
  seed: 42
  weighted_clauses: false
  y_max: -10
  y_min: -80
dataset_file_name: acrobot_obs_data
env_name: acrobot
epochs: 3
exploration_prob_decay: 0.001
exploration_prob_init: 0.7
gamma: 0.982
obs_space_size: 6
save: true
soft_update_type: soft_update_2
test_freq: 1
threshold: -495
update_freq: 4
