wandb_version: 1

gamma:
  value: 0.7665650333528679
nr_of_clauses:
  value: 1772
number_of_state_bits_ta:
  value: 7
specificity:
  value: 2.227690188102649
threshold:
  value: 0.4281655400893119
total_bits_per_feature:
  value: 4
update_freq:
  value: 13
y_max:
  value: 63
y_min:
  value: 9
