wandb_version: 1

gamma:
  value: 0.5355172424878252
nr_of_clauses:
  value: 2014
number_of_state_bits_ta:
  value: 10
specificity:
  value: 9.028687670720185
threshold:
  value: 0.042734226625601446
total_bits_per_feature:
  value: 12
update_freq:
  value: 2
y_max:
  value: 80
y_min:
  value: 3
