wandb_version: 1

batch_size:
  value: 96
bits_per_feature:
  value: 6
buffer_size:
  value: 5000
epochs:
  value: 6
gamma:
  value: 0.98
nr_of_clauses:
  value: 1140
number_of_state_bits_ta:
  value: 4
specificity:
  value: 3.8300000000000023
t:
  value: 0.18000000000000002
update_freq:
  value: 4
y_max:
  value: 65
y_min:
  value: 20
