wandb_version: 1

batch_size:
  value: 16
bits_per_feature:
  value: 12
buffer_size:
  value: 500
epochs:
  value: 4
gamma:
  value: 0.929
nr_of_clauses:
  value: 1140
number_of_state_bits_ta:
  value: 6
specificity:
  value: 9.260000000000009
t:
  value: 0.21
update_freq:
  value: 9
y_max:
  value: 75
y_min:
  value: 20
