action_space_size: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  AwAAAAAAAAA=
actor:
  T: 450
  bits_per_feature: 14
  device: CPU
  nr_of_clauses: 1960
  number_of_state_bits_ta: 8
  s: 7.880000000000006
  seed: 42
  weighted_clauses: false
algorithm: TAC_a
batch_size: 112
buffer_size: 5000
critic:
  T: 954
  bits_per_feature: 12
  device: CPU
  max_update_p: 0.053000000000000005
  nr_of_clauses: 1150
  number_of_state_bits_ta: 8
  s: 6.700000000000005
  seed: 42
  weighted_clauses: false
  y_max: -10
  y_min: -70
dataset_file_name: acrobot_obs_data
env_name: acrobot
epochs: 3
exploration_prob_decay: 0.001
exploration_prob_init: 0.8999999999999999
gamma: 0.944
obs_space_size: 6
save: true
soft_update_type: soft_update_1
test_freq: 1
threshold: -495
update_grad: 0.139
