action_space_size: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  AwAAAAAAAAA=
actor:
  T: 770
  bits_per_feature: 10
  device: CPU
  nr_of_clauses: 1000
  number_of_state_bits_ta: 9
  s: 1.6900000000000006
  seed: 42
  weighted_clauses: false
algorithm: TAC_random
batch_size: 96
buffer_size: 2000
critic:
  T: 432
  bits_per_feature: 13
  device: CPU
  max_update_p: 0.036000000000000004
  nr_of_clauses: 1350
  number_of_state_bits_ta: 4
  s: 9.890000000000008
  seed: 42
  weighted_clauses: false
  y_max: -5
  y_min: -80
dataset_file_name: acrobot_obs_data
env_name: acrobot
epochs: 5
exploration_prob_decay: 0.001
exploration_prob_init: 0.8999999999999999
gamma: 0.919
obs_space_size: 6
save: true
soft_update_type: soft_update_1
test_freq: 1
threshold: -495
update_grad: 0.677
