T: 333.20000000000005
algorithm: n_step_Double_TMQN
batch_size: 80
bits_per_feature: 9
buffer_size: 4000
device: CPU
epochs: 2
exploration_prob_decay: 0.001
exploration_prob_init: 1.0
gamma: 0.992
n_steps: 17
nr_of_clauses: 980
nr_of_episodes: 10000
nr_of_steps: 3420431
number_of_state_bits_ta: 6
s: 8.58
save: true
soft_update_type: soft_update_2
test_freq: 1
update_freq: 8
update_grad: 0.05
weighted_clauses: false
y_max: 60
y_min: 20
