wandb_version: 1

gamma:
  value: 0.9291967781374828
nr_of_clauses:
  value: 335
number_of_state_bits_ta:
  value: 19
specificity:
  value: 9.036639433765838
threshold:
  value: 0.43325010882600545
total_bits_per_feature:
  value: 2
update_freq:
  value: 22
y_max:
  value: 79
y_min:
  value: 39
