wandb_version: 1

gamma:
  value: 0.7338199248062462
nr_of_clauses:
  value: 1104
number_of_state_bits_ta:
  value: 25
specificity:
  value: 7.569072618596373
threshold:
  value: 0.7215413656051382
total_bits_per_feature:
  value: 10
update_freq:
  value: 6
y_max:
  value: 95
y_min:
  value: 4
