wandb_version: 1

gamma:
  value: 0.6077763805395071
nr_of_clauses:
  value: 1591
number_of_state_bits_ta:
  value: 2
specificity:
  value: 8.49271833592994
threshold:
  value: 0.9125813278838044
total_bits_per_feature:
  value: 5
update_freq:
  value: 13
y_max:
  value: 80
y_min:
  value: 15
