wandb_version: 1

gamma:
  value: 0.6190616072998939
nr_of_clauses:
  value: 1283
number_of_state_bits_ta:
  value: 4
specificity:
  value: 7.908341911627771
threshold:
  value: 0.3711001595253657
total_bits_per_feature:
  value: 1
update_freq:
  value: 17
y_max:
  value: 61
y_min:
  value: 36
