wandb_version: 1

gamma:
  value: 0.8519130822738943
nr_of_clauses:
  value: 1814
number_of_state_bits_ta:
  value: 21
specificity:
  value: 6.9194191308580955
threshold:
  value: 0.9023914751373342
total_bits_per_feature:
  value: 3
update_freq:
  value: 15
y_max:
  value: 100
y_min:
  value: 20
