wandb_version: 1

gamma:
  value: 0.641116483437076
nr_of_clauses:
  value: 1836
number_of_state_bits_ta:
  value: 22
specificity:
  value: 7.785518662905635
threshold:
  value: 0.0677037305982144
total_bits_per_feature:
  value: 7
update_freq:
  value: 1
y_max:
  value: 87
y_min:
  value: 25
