wandb_version: 1

gamma:
  value: 0.9292985872677176
nr_of_clauses:
  value: 1110
number_of_state_bits_ta:
  value: 15
specificity:
  value: 1.0489790269246229
threshold:
  value: 0.6730407201203128
total_bits_per_feature:
  value: 4
update_freq:
  value: 4
y_max:
  value: 96
y_min:
  value: 4
