wandb_version: 1

gamma:
  value: 0.8973418822948467
nr_of_clauses:
  value: 1600
number_of_state_bits_ta:
  value: 16
specificity:
  value: 1.427038844342893
threshold:
  value: 0.6918785488060402
total_bits_per_feature:
  value: 5
update_freq:
  value: 18
y_max:
  value: 99
y_min:
  value: 28
