wandb_version: 1

gamma:
  value: 0.6266245243917417
nr_of_clauses:
  value: 1689
number_of_state_bits_ta:
  value: 16
specificity:
  value: 8.71689972040718
threshold:
  value: 0.10636185864269956
total_bits_per_feature:
  value: 7
update_freq:
  value: 11
y_max:
  value: 62
y_min:
  value: 14
