wandb_version: 1

gamma:
  value: 0.8289876583926585
nr_of_clauses:
  value: 794
number_of_state_bits_ta:
  value: 15
specificity:
  value: 2.590950060537598
threshold:
  value: 0.5835269517372434
total_bits_per_feature:
  value: 6
update_freq:
  value: 26
y_max:
  value: 62
y_min:
  value: 3
