wandb_version: 1

gamma:
  value: 0.7539789537778026
nr_of_clauses:
  value: 1312
number_of_state_bits_ta:
  value: 18
specificity:
  value: 5.795932328264347
threshold:
  value: 0.032730902264643556
total_bits_per_feature:
  value: 13
update_freq:
  value: 14
y_max:
  value: 76
y_min:
  value: 37
