wandb_version: 1

gamma:
  value: 0.8505945298337355
nr_of_clauses:
  value: 868
number_of_state_bits_ta:
  value: 20
specificity:
  value: 2.459805725116228
threshold:
  value: 0.26193752001054077
total_bits_per_feature:
  value: 9
update_freq:
  value: 10
y_max:
  value: 95
y_min:
  value: 24
