wandb_version: 1

gamma:
  value: 0.949452253084052
nr_of_clauses:
  value: 1335
number_of_state_bits_ta:
  value: 7
specificity:
  value: 9.530926010021831
threshold:
  value: 0.159023284554558
total_bits_per_feature:
  value: 20
update_freq:
  value: 21
y_max:
  value: 71
y_min:
  value: 5
