wandb_version: 1

gamma:
  value: 0.6105244069082676
nr_of_clauses:
  value: 1144
number_of_state_bits_ta:
  value: 1
specificity:
  value: 8.335152643151595
threshold:
  value: 0.5092808304435309
total_bits_per_feature:
  value: 4
update_freq:
  value: 16
y_max:
  value: 74
y_min:
  value: 25
