wandb_version: 1

gamma:
  value: 0.6980477137261889
nr_of_clauses:
  value: 2207
number_of_state_bits_ta:
  value: 8
specificity:
  value: 3.750378510710512
threshold:
  value: 0.551589574954148
total_bits_per_feature:
  value: 1
update_freq:
  value: 4
y_max:
  value: 96
y_min:
  value: 40
