wandb_version: 1

gamma:
  value: 0.5335860088271007
nr_of_clauses:
  value: 2429
number_of_state_bits_ta:
  value: 23
specificity:
  value: 5.726751892491954
threshold:
  value: 0.644465273329166
total_bits_per_feature:
  value: 11
update_freq:
  value: 21
y_max:
  value: 65
y_min:
  value: 14
