wandb_version: 1

gamma:
  value: 0.728628661642394
nr_of_clauses:
  value: 878
number_of_state_bits_ta:
  value: 10
specificity:
  value: 8.88603661763597
threshold:
  value: 0.4927769874133054
total_bits_per_feature:
  value: 17
update_freq:
  value: 24
y_max:
  value: 83
y_min:
  value: 14
