wandb_version: 1

gamma:
  value: 0.7659224392533388
nr_of_clauses:
  value: 1496
number_of_state_bits_ta:
  value: 14
specificity:
  value: 7.340863348753798
threshold:
  value: 0.8745702536474106
total_bits_per_feature:
  value: 4
update_freq:
  value: 28
y_max:
  value: 84
y_min:
  value: 25
