wandb_version: 1

gamma:
  value: 0.730253203674922
nr_of_clauses:
  value: 1897
number_of_state_bits_ta:
  value: 16
specificity:
  value: 3.863367344464175
threshold:
  value: 0.06679391376157402
total_bits_per_feature:
  value: 19
update_freq:
  value: 6
y_max:
  value: 73
y_min:
  value: 32
