wandb_version: 1

gamma:
  value: 0.909122010247606
nr_of_clauses:
  value: 1523
number_of_state_bits_ta:
  value: 4
specificity:
  value: 2.712698339622033
threshold:
  value: 0.4222971563122477
total_bits_per_feature:
  value: 6
update_freq:
  value: 16
y_max:
  value: 70
y_min:
  value: 18
