wandb_version: 1

gamma:
  value: 0.5235450639738934
nr_of_clauses:
  value: 1307
number_of_state_bits_ta:
  value: 25
specificity:
  value: 7.900834188991316
threshold:
  value: 0.3270865414991853
total_bits_per_feature:
  value: 18
update_freq:
  value: 14
y_max:
  value: 94
y_min:
  value: 13
