wandb_version: 1

gamma:
  value: 0.6416728987085785
nr_of_clauses:
  value: 1749
number_of_state_bits_ta:
  value: 15
specificity:
  value: 5.440528334537092
threshold:
  value: 0.6665316159922853
total_bits_per_feature:
  value: 9
update_freq:
  value: 29
y_max:
  value: 92
y_min:
  value: 5
