wandb_version: 1

gamma:
  value: 0.7759387451812038
nr_of_clauses:
  value: 1985
number_of_state_bits_ta:
  value: 6
specificity:
  value: 2.265337798093454
threshold:
  value: 0.8424086381907078
total_bits_per_feature:
  value: 11
update_freq:
  value: 22
y_max:
  value: 60
y_min:
  value: 32
