wandb_version: 1

gamma:
  value: 0.6059279778616676
nr_of_clauses:
  value: 1694
number_of_state_bits_ta:
  value: 22
specificity:
  value: 7.137161805070915
threshold:
  value: 0.11335124647620765
total_bits_per_feature:
  value: 14
update_freq:
  value: 18
y_max:
  value: 80
y_min:
  value: 33
