wandb_version: 1

gamma:
  value: 0.5699769008827109
nr_of_clauses:
  value: 408
number_of_state_bits_ta:
  value: 25
specificity:
  value: 7.10058219622313
threshold:
  value: 0.7781246308751025
total_bits_per_feature:
  value: 11
update_freq:
  value: 5
y_max:
  value: 65
y_min:
  value: 4
