wandb_version: 1

gamma:
  value: 0.8403203101799578
nr_of_clauses:
  value: 787
number_of_state_bits_ta:
  value: 18
specificity:
  value: 3.7040553692196343
threshold:
  value: 0.7144388135419547
total_bits_per_feature:
  value: 2
update_freq:
  value: 22
y_max:
  value: 93
y_min:
  value: 27
