wandb_version: 1

gamma:
  value: 0.973728764828156
nr_of_clauses:
  value: 2197
number_of_state_bits_ta:
  value: 2
specificity:
  value: 1.735140032439348
threshold:
  value: 0.19754521638717143
total_bits_per_feature:
  value: 4
update_freq:
  value: 24
y_max:
  value: 97
y_min:
  value: 28
