wandb_version: 1

gamma:
  value: 0.7206936193699149
nr_of_clauses:
  value: 1528
number_of_state_bits_ta:
  value: 17
specificity:
  value: 9.00275407988913
threshold:
  value: 0.9015813521201572
total_bits_per_feature:
  value: 17
update_freq:
  value: 26
y_max:
  value: 72
y_min:
  value: 35
