wandb_version: 1

gamma:
  value: 0.9979953858725568
nr_of_clauses:
  value: 718
number_of_state_bits_ta:
  value: 9
specificity:
  value: 9.80861195015113
threshold:
  value: 0.8578588678912618
total_bits_per_feature:
  value: 14
update_freq:
  value: 6
y_max:
  value: 60
y_min:
  value: 20
