actor:
  T: 928
  bits_per_feature: 12
  device: CPU
  nr_of_classes: 2
  nr_of_clauses: 1160
  number_of_state_bits_ta: 3
  s: 1.43
  seed: 42
  weighted_clauses: false
algorithm: TM_DDPG_2
batch_size: 112
buffer_size: 9352
critic:
  T: 270
  bits_per_feature: 12
  device: CPU
  nr_of_clauses: 1000
  number_of_state_bits_ta: 3
  s: 5.42
  seed: 42
  weighted_clauses: false
  y_max: 60
  y_min: 35
epochs: 7
exploration_prob_decay: 0.001
exploration_prob_init: 1.0
gamma: 0.998
save: true
soft_update_type: soft_update_2
test_freq: 1
update_freq: 4
update_grad: -1
