wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1707315051.995904
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.0
      5: 0.16.3
      8:
      - 3
      - 5
      13: windows-amd64
gamma:
  desc: null
  value: 0.9513040795673112
nr_of_clauses:
  desc: null
  value: 1906
number_of_state_bits_ta:
  desc: null
  value: 5
specificity:
  desc: null
  value: 3.876733208185798
threshold:
  desc: null
  value: 0.8595381705835854
total_bits_per_feature:
  desc: null
  value: 11
update_freq:
  desc: null
  value: 30
y_max:
  desc: null
  value: 74
y_min:
  desc: null
  value: 15
