action_space_size: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  AgAAAAAAAAA=
actor:
  T: 656
  bits_per_feature: 14
  max_update_p: 0.002
  min_update_p: 0.0008
  nr_of_clauses: 980
  number_of_state_bits_ta: 6
  s: 1.2300000000000002
  y_max: 100
  y_min: 0
algorithm: TPPO
batch_size: 256
critic:
  T: 986
  bits_per_feature: 12
  max_update_p: 0.014000000000000002
  min_update_p: 0.0
  nr_of_clauses: 1430
  number_of_state_bits_ta: 7
  s: 2.0900000000000007
  y_max: 24.5
  y_min: 0.5
dataset_file_name: observation_data
device: CPU
env_name: cartpole
epochs: 2
gamma: 0.923
lam: 0.99
n_timesteps: 1000
obs_space_size: 4
save: true
seed: 42
test_freq: 1
threshold: 20
weighted_clauses: false
