action_space_size: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  AgAAAAAAAAA=
actor:
  T: 1144
  bits_per_feature: 8
  max_update_p: 0.066
  min_update_p: 0.0007000000000000001
  nr_of_clauses: 1300
  number_of_state_bits_ta: 4
  s: 2.5900000000000016
  y_max: 100
  y_min: 0
algorithm: TPPO
batch_size: 240
critic:
  T: 495
  bits_per_feature: 10
  max_update_p: 0.060000000000000005
  min_update_p: 0.0
  nr_of_clauses: 1180
  number_of_state_bits_ta: 6
  s: 2.9700000000000015
  y_max: 34
  y_min: 0.1
dataset_file_name: observation_data
device: CPU
env_name: cartpole
epochs: 2
gamma: 0.944
lam: 0.935
n_timesteps: 68
obs_space_size: 4
save: true
seed: 42
test_freq: 1
threshold: 20
weighted_clauses: false
