wandb_version: 1

batch_size:
  value: 112
bits_per_feature:
  value: 11
buffer_size:
  value: 9000
epochs:
  value: 1
gamma:
  value: 0.961
nr_of_clauses:
  value: 1120
number_of_state_bits_ta:
  value: 3
specificity:
  value: 8.570000000000007
t:
  value: 0.47
update_freq:
  value: 4
y_max:
  value: 70
y_min:
  value: 35
