wandb_version: 1

batch_size:
  value: 32
bits_per_feature:
  value: 8
buffer_size:
  value: 4500
epochs:
  value: 4
gamma:
  value: 0.954
nr_of_clauses:
  value: 840
number_of_state_bits_ta:
  value: 4
specificity:
  value: 6.800000000000005
t:
  value: 0.86
update_freq:
  value: 4
y_max:
  value: 75
y_min:
  value: 35
