action_space_size: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  AgAAAAAAAAA=
algorithm: n_step_DQN
batch_size: 128
buffer_size: 5000
c: 0
env_name: cartpole
epochs: 8
exploration_prob_decay: 0.005
exploration_prob_init: 1.0
gamma: 0.99
hidden_size: 160
learning_rate: 0.003
n_steps: 15
obs_space_size: 4
save: true
test_freq: 1
