wandb_version: 1

gamma:
  value: 0.8784513914713103
nr_of_clauses:
  value: 656
number_of_state_bits_ta:
  value: 1
specificity:
  value: 1.2595468220389785
threshold:
  value: 0.5218633512496125
total_bits_per_feature:
  value: 5
update_freq:
  value: 5
y_max:
  value: 77
y_min:
  value: 14
