action_space_size: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  AgAAAAAAAAA=
actor:
  T: 637
  bits_per_feature: 10
  device: CPU
  nr_of_clauses: 980
  number_of_state_bits_ta: 9
  s: 3.8600000000000025
  seed: 42
  weighted_clauses: false
algorithm: TAC_random
batch_size: 80
buffer_size: 3000
critic:
  T: 744
  bits_per_feature: 11
  device: CPU
  max_update_p: 0.069
  nr_of_clauses: 1550
  number_of_state_bits_ta: 9
  s: 5.400000000000004
  seed: 42
  weighted_clauses: false
  y_max: 75
  y_min: 35
dataset_file_name: observation_data
env_name: cartpole
epochs: 4
exploration_prob_decay: 0.008
exploration_prob_init: 0.8
gamma: 0.916
obs_space_size: 4
save: true
soft_update_type: soft_update_1
test_freq: 1
threshold: 20
update_grad: 0.785
