wandb_version: 1

gamma:
  value: 0.9237293468211648
nr_of_clauses:
  value: 1321
number_of_state_bits_ta:
  value: 18
specificity:
  value: 9.512169916310093
threshold:
  value: 0.6403903007296007
total_bits_per_feature:
  value: 11
update_freq:
  value: 7
y_max:
  value: 72
y_min:
  value: 28
