wandb_version: 1

gamma:
  value: 0.5522711010576399
nr_of_clauses:
  value: 1279
number_of_state_bits_ta:
  value: 18
specificity:
  value: 4.212960729698775
threshold:
  value: 0.8788173033110411
total_bits_per_feature:
  value: 14
update_freq:
  value: 9
y_max:
  value: 97
y_min:
  value: 35
