wandb_version: 1

batch_size:
  value: 112
bits_per_feature:
  value: 9
buffer_size:
  value: 9000
epochs:
  value: 6
gamma:
  value: 0.984
n_steps:
  value: 8
nr_of_clauses:
  value: 1040
number_of_state_bits_ta:
  value: 8
specificity:
  value: 5.570000000000004
t:
  value: 0.96
update_freq:
  value: 2
y_max:
  value: 70
y_min:
  value: 30
