wandb_version: 1

batch_size:
  value: 32
bits_per_feature:
  value: 5
buffer_size:
  value: 1500
epochs:
  value: 1
gamma:
  value: 0.999
n_steps:
  value: 15
nr_of_clauses:
  value: 1040
number_of_state_bits_ta:
  value: 3
specificity:
  value: 9.140000000000008
t:
  value: 0.97
update_freq:
  value: 9
y_max:
  value: 60
y_min:
  value: 30
