wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1707340028.271824
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 23
      - 37
      4: 3.10.0
      5: 0.16.3
      8:
      - 3
      - 5
      13: windows-amd64
gamma:
  desc: null
  value: 0.7539789537778026
nr_of_clauses:
  desc: null
  value: 1312
number_of_state_bits_ta:
  desc: null
  value: 18
specificity:
  desc: null
  value: 5.795932328264347
threshold:
  desc: null
  value: 0.032730902264643556
total_bits_per_feature:
  desc: null
  value: 13
update_freq:
  desc: null
  value: 14
y_max:
  desc: null
  value: 76
y_min:
  desc: null
  value: 37
