T: 499
action_space_size: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  AgAAAAAAAAA=
algorithm: n_step_QTM
batch_size: 16
bits_per_feature: 10
buffer_size: 4000
dataset_file_name: observation_data
device: CPU
dynamic_memory: false
env_name: cartpole
epochs: 7
exploration_prob_decay: 0.009
exploration_prob_init: 0.9
gamma: 0.979
max_update_p: 0.156
min_update_p: 0.0
n_steps: 15
nr_of_clauses: 1040
number_of_state_bits_ta: 5
obs_space_size: 4
s: 5.84
save: true
test_freq: 1
threshold: 0
weighted_clauses: false
y_max: 75
y_min: 25
