T: 743
algorithm: TM_PPO
batch_size: 64
bits_per_feature: 11
clip: 0.041
comment: --Does not use normalization--
device: CPU
epochs: 1
gamma: 0.961
lam: 0.95
nr_of_clauses: 1110
number_of_state_bits_ta: 4
s: 1.66
save: true
seed: 42
test_freq: 1
weighted_clauses: false
y_max: 2.0
y_min: 0.0
