T: 387
algorithm: TM_PPO
batch_size: 64
bits_per_feature: 7
clip: 0.121
device: CPU
epochs: 3
gamma: 0.952
lam: 0.964
nr_of_clauses: 1020
number_of_state_bits_ta: 4
s: 2.22
save: true
seed: 42
test_freq: 1
weighted_clauses: false
y_max: 2.0
y_min: 0.0
