wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709106154.90007
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.0
      5: 0.16.3
      8:
      - 3
      - 5
      13: windows-amd64
batch_size:
  desc: null
  value: 16
bits_per_feature:
  desc: null
  value: 6
buffer_size:
  desc: null
  value: 3500
epochs:
  desc: null
  value: 1
gamma:
  desc: null
  value: 0.952
n_steps:
  desc: null
  value: 11
nr_of_clauses:
  desc: null
  value: 940
number_of_state_bits_ta:
  desc: null
  value: 3
specificity:
  desc: null
  value: 3.9700000000000024
t:
  desc: null
  value: 0.41
update_freq:
  desc: null
  value: 7
y_max:
  desc: null
  value: 75
y_min:
  desc: null
  value: 20
