T: 804
action_space_size: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  AwAAAAAAAAA=
algorithm: n_step_QTM
batch_size: 80
bits_per_feature: 13
buffer_size: 1000
dataset_file_name: acrobot_obs_data
device: CPU
env_name: acrobot
epochs: 4
exploration_prob_decay: 0.007
exploration_prob_init: 0.6
gamma: 0.933
max_update_p: 0.186
min_update_p: 0
n_steps: 26
nr_of_clauses: 1200
number_of_state_bits_ta: 3
obs_space_size: 6
s: 1.3600000000000003
save: true
seed: 42
test_freq: 1
threshold: -495
weighted_clauses: false
y_max: -10
y_min: -75
