actor:
  T: 652
  bits_per_feature: 5
  device: CPU
  nr_of_classes: 2
  nr_of_clauses: 1020
  number_of_state_bits_ta: 9
  s: 1.52
  seed: 42
  weighted_clauses: false
algorithm: TM_DDPG_2
batch_size: 80
critic:
  T: 66
  bits_per_feature: 9
  device: CPU
  nr_of_clauses: 1100
  number_of_state_bits_ta: 3
  s: 3.69
  seed: 42
  weighted_clauses: false
  y_max: 60
  y_min: 35
epochs: 5
exploration_prob_decay: 0.001
exploration_prob_init: 1.0
gamma: 0.981
save: true
soft_update_type: soft_update_1
test_freq: 1
update_grad: 0.724
