action_space_size: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  AgAAAAAAAAA=
actor:
  T: 418
  bits_per_feature: 7
  device: CPU
  nr_of_clauses: 820
  number_of_state_bits_ta: 9
  s: 1.06
  seed: 42
  weighted_clauses: false
algorithm: TAC_a
batch_size: 80
buffer_size: 7000
critic:
  T: 388
  bits_per_feature: 11
  device: CPU
  max_update_p: 0.018000000000000002
  nr_of_clauses: 1050
  number_of_state_bits_ta: 3
  s: 2.4700000000000015
  seed: 42
  weighted_clauses: false
  y_max: 75
  y_min: 35
dataset_file_name: observation_data
env_name: cartpole
epochs: 6
exploration_prob_decay: 0.005
exploration_prob_init: 0.9
gamma: 0.976
obs_space_size: 4
save: true
soft_update_type: soft_update_1
test_freq: 1
threshold: 20
update_grad: 0.722
