T: 519
algorithm: n_step_Double_TMQN
batch_size: 32
bits_per_feature: 5
buffer_size: 9000
device: CPU
epochs: 5
exploration_prob_decay: 0.001
exploration_prob_init: 1.0
gamma: 0.976
n_steps: 15
nr_of_clauses: 880
nr_of_episodes: 10000
nr_of_steps: 3980596
number_of_state_bits_ta: 8
s: 9.26
save: true
soft_update_type: soft_update_1
test_freq: 1
update_freq: 9999
update_grad: 0.859
weighted_clauses: false
y_max: 75
y_min: 20
