T: 862
algorithm: TM_PPO
batch_size: 480
bits_per_feature: 6
clip: 0.011
comment: --Does not use normalization--
device: CPU
epochs: 1
gamma: 0.979
lam: 0.976
nr_of_clauses: 1150
number_of_state_bits_ta: 6
s: 1.56
save: true
seed: 42
test_freq: 1
weighted_clauses: false
y_max: 100.0
y_min: 0.0
