wandb_version: 1

gamma:
  value: 0.5933891554474084
nr_of_clauses:
  value: 106
number_of_state_bits_ta:
  value: 25
specificity:
  value: 7.881716360269499
threshold:
  value: 0.6091816627948161
total_bits_per_feature:
  value: 18
update_freq:
  value: 9
y_max:
  value: 94
y_min:
  value: 25
