wandb_version: 1

gamma:
  value: 0.6806324304635343
nr_of_clauses:
  value: 1704
number_of_state_bits_ta:
  value: 3
specificity:
  value: 6.2589590683854475
threshold:
  value: 0.3776101190670469
total_bits_per_feature:
  value: 9
update_freq:
  value: 12
y_max:
  value: 61
y_min:
  value: 20
