action_space_size: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  AwAAAAAAAAA=
actor:
  T: 415
  bits_per_feature: 12
  device: CPU
  nr_of_clauses: 1660
  number_of_state_bits_ta: 3
  s: 7.130000000000005
  seed: 42
  weighted_clauses: false
algorithm: TAC_b
batch_size: 112
buffer_size: 8500
critic:
  T: 1584
  bits_per_feature: 7
  device: CPU
  max_update_p: 0.012
  nr_of_clauses: 1650
  number_of_state_bits_ta: 9
  s: 1.01
  seed: 42
  weighted_clauses: false
  y_max: -25
  y_min: -75
dataset_file_name: acrobot_obs_data
env_name: acrobot
epochs: 1
exploration_prob_decay: 0.006
exploration_prob_init: 0.7999999999999999
gamma: 0.949
obs_space_size: 6
save: true
soft_update_type: soft_update_2
test_freq: 1
threshold: -500
update_freq: 8
