action_space_size: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  AwAAAAAAAAA=
actor:
  T: 1300
  bits_per_feature: 6
  device: CPU
  nr_of_clauses: 1500
  number_of_state_bits_ta: 6
  s: 2.01
  seed: 42
algorithm: TAC_b
batch_size: 1
buffer_size: 10000
critic:
  T: 1306
  bits_per_feature: 6
  device: CPU
  max_update_p: 0.01
  nr_of_clauses: 1500
  number_of_state_bits_ta: 6
  s: 3.290000000000002
  seed: 42
  y_max: 0
  y_min: -100
dataset_file_name: acrobot_obs_data
env_name: acrobot
epsilon_decay: 0.001
epsilon_init: 1.0
gamma: 0.99
obs_space_size: 6
sampling_iterations: 64
save: true
soft_update_type: soft_update_b
test_freq: 5
threshold: -495
update_freq: 8
