action_space_size: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  AgAAAAAAAAA=
actor:
  T: 828
  bits_per_feature: 14
  max_update_p: 0.035
  min_update_p: 0.0005
  nr_of_clauses: 1380
  number_of_state_bits_ta: 4
  s: 1.33
  y_max: 100
  y_min: 0
algorithm: TPPO
batch_size: 144
critic:
  T: 480
  bits_per_feature: 7
  max_update_p: 0.017
  min_update_p: 0.0
  nr_of_clauses: 980
  number_of_state_bits_ta: 3
  s: 1.12
  y_max: 30
  y_min: 0.4
dataset_file_name: observation_data
device: CPU
env_name: cartpole
epochs: 1
gamma: 0.968
lam: 0.974
n_timesteps: 124
obs_space_size: 4
save: true
seed: 42
test_freq: 1
threshold: -500
weighted_clauses: false
