T: 825
algorithm: n_step_TMQN
batch_size: 96
bits_per_feature: 5
buffer_size: 9500
device: CPU
dynamic_memory: false
epochs: 6
exploration_prob_decay: 0.001
exploration_prob_init: 1.0
gamma: 0.987
n_steps: 16
nr_of_clauses: 960
nr_of_episodes: 10000
nr_of_steps: 1739942
number_of_state_bits_ta: 8
s: 5.37
save: true
test_freq: 1
weighted_clauses: false
y_max: 75
y_min: 30
