actor:
  T: 636
  bits_per_feature: 10
  device: CPU
  nr_of_classes: 2
  nr_of_clauses: 860
  number_of_state_bits_ta: 5
  s: 1.61
  seed: 42
  weighted_clauses: false
algorithm: TM_DDPG_2
batch_size: 80
buffer_size: 6292
critic:
  T: 693
  bits_per_feature: 8
  device: CPU
  nr_of_clauses: 1650
  number_of_state_bits_ta: 5
  s: 3.29
  seed: 42
  weighted_clauses: false
  y_max: 70
  y_min: 25
epochs: 7
exploration_prob_decay: 0.001
exploration_prob_init: 1.0
gamma: 0.913
save: true
soft_update_type: soft_update_1
test_freq: 1
update_grad: 0.55
