wandb_version: 1

batch_size:
  value: 96
bits_per_feature:
  value: 14
buffer_size:
  value: 9000
epochs:
  value: 5
gamma:
  value: 0.977
n_steps:
  value: 6
nr_of_clauses:
  value: 940
number_of_state_bits_ta:
  value: 6
specificity:
  value: 7.720000000000006
t:
  value: 0.12
update_freq:
  value: 8
y_max:
  value: 70
y_min:
  value: 30
