wandb_version: 1

batch_size:
  value: 112
bits_per_feature:
  value: 8
buffer_size:
  value: 4500
epochs:
  value: 1
gamma:
  value: 0.911
n_steps:
  value: 15
nr_of_clauses:
  value: 840
number_of_state_bits_ta:
  value: 7
specificity:
  value: 7.900000000000006
t:
  value: 0.36000000000000004
update_freq:
  value: 6
y_max:
  value: 60
y_min:
  value: 25
