action_space_size: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  AgAAAAAAAAA=
actor:
  T: 506
  bits_per_feature: 13
  device: CPU
  nr_of_clauses: 1100
  number_of_state_bits_ta: 6
  s: 3.6800000000000024
  seed: 42
  weighted_clauses: false
algorithm: TAC_b
batch_size: 48
buffer_size: 1000
critic:
  T: 513
  bits_per_feature: 6
  device: CPU
  max_update_p: 0.056
  nr_of_clauses: 1350
  number_of_state_bits_ta: 9
  s: 7.470000000000006
  seed: 42
  weighted_clauses: false
  y_max: 75
  y_min: 30
dataset_file_name: observation_data
env_name: cartpole
epochs: 6
exploration_prob_decay: 0.002
exploration_prob_init: 0.9
gamma: 0.982
obs_space_size: 4
save: true
soft_update_type: soft_update_2
test_freq: 1
threshold: 20
update_freq: 3
