T: 404
algorithm: n_step_TMQN
batch_size: 48
bits_per_feature: 11
buffer_size: 9500
device: CPU
dynamic_memory: false
epochs: 4
exploration_prob_decay: 0.001
exploration_prob_init: 1.0
gamma: 0.98
n_steps: 18
nr_of_clauses: 880
nr_of_episodes: 10000
nr_of_steps: 3255629
number_of_state_bits_ta: 9
s: 8.88
save: true
test_freq: 1
weighted_clauses: false
y_max: 70
y_min: 25
