T: 561
action_space_size: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  AgAAAAAAAAA=
algorithm: n_step_QTM
batch_size: 96
bits_per_feature: 10
buffer_size: 7500
dataset_file_name: observation_data
device: CPU
env_name: cartpole
epochs: 1
exploration_prob_decay: 0.003
exploration_prob_init: 0.9
gamma: 0.978
max_update_p: 0.176
min_update_p: 0
n_steps: 15
nr_of_clauses: 1020
number_of_state_bits_ta: 7
obs_space_size: 4
s: 3.1
save: true
seed: 42
test_freq: 1
threshold: 15
weighted_clauses: false
y_max: 65
y_min: 25
