T: 691.2
algorithm: n_step_Double_TMQN
batch_size: 96
bits_per_feature: 5
buffer_size: 500
device: CPU
epochs: 4
exploration_prob_decay: 0.001
exploration_prob_init: 1.0
gamma: 0.966
n_steps: 19
nr_of_clauses: 1080
nr_of_episodes: 10000
nr_of_steps: 3869175
number_of_state_bits_ta: 8
s: 9.92
save: true
soft_update_type: soft_update_1
test_freq: 1
update_freq: 9999999
update_grad: 0.129
weighted_clauses: false
y_max: 70
y_min: 20
