wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1707327942.282978
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.0
      5: 0.16.3
      8:
      - 3
      - 5
      13: windows-amd64
gamma:
  desc: null
  value: 0.8289876583926585
nr_of_clauses:
  desc: null
  value: 794
number_of_state_bits_ta:
  desc: null
  value: 15
specificity:
  desc: null
  value: 2.590950060537598
threshold:
  desc: null
  value: 0.5835269517372434
total_bits_per_feature:
  desc: null
  value: 6
update_freq:
  desc: null
  value: 26
y_max:
  desc: null
  value: 62
y_min:
  desc: null
  value: 3
