T: 478
algorithm: Double_TMQN
batch_size: 16
bits_per_feature: 12
buffer_size: 1500
device: CPU
dynamic_memory: false
epochs: 6
exploration_prob_decay: 0.001
exploration_prob_init: 1.0
gamma: 0.981
min_feedback_p: 1.0
nr_of_clauses: 920
nr_of_episodes: 10000
nr_of_steps: 3682946
number_of_state_bits_ta: 8
s: 5.12
save: true
seed: 42
soft_update_type: soft_update_1
test_freq: 1
update_freq: -1
update_grad: 0.346
weighted_clauses: false
y_max: 65
y_min: 20
