wandb_version: 1

batch_size:
  value: 32
bits_per_feature:
  value: 12
buffer_size:
  value: 4000
epochs:
  value: 5
gamma:
  value: 0.954
n_steps:
  value: 18
nr_of_clauses:
  value: 1040
number_of_state_bits_ta:
  value: 4
specificity:
  value: 4.130000000000003
t:
  value: 0.78
update_freq:
  value: 9
y_max:
  value: 60
y_min:
  value: 25
