wandb_version: 1

batch_size:
  value: 16
bits_per_feature:
  value: 8
buffer_size:
  value: 3500
epochs:
  value: 2
gamma:
  value: 0.905
n_steps:
  value: 1
nr_of_clauses:
  value: 960
number_of_state_bits_ta:
  value: 3
specificity:
  value: 3.5900000000000025
t:
  value: 0.19
update_freq:
  value: 9
y_max:
  value: 75
y_min:
  value: 30
