wandb_version: 1

batch_size:
  value: 32
bits_per_feature:
  value: 10
buffer_size:
  value: 2000
epochs:
  value: 3
gamma:
  value: 0.942
n_steps:
  value: 18
nr_of_clauses:
  value: 1160
number_of_state_bits_ta:
  value: 8
specificity:
  value: 6.9500000000000055
t:
  value: 0.06999999999999999
update_freq:
  value: 6
y_max:
  value: 65
y_min:
  value: 30
