wandb_version: 1

batch_size:
  value: 48
bits_per_feature:
  value: 14
buffer_size:
  value: 3000
epochs:
  value: 4
gamma:
  value: 0.917
n_steps:
  value: 11
nr_of_clauses:
  value: 1100
number_of_state_bits_ta:
  value: 6
specificity:
  value: 2.370000000000001
t:
  value: 0.51
update_freq:
  value: 4
y_max:
  value: 60
y_min:
  value: 25
