wandb_version: 1

batch_size:
  value: 16
bits_per_feature:
  value: 13
buffer_size:
  value: 9000
epochs:
  value: 6
gamma:
  value: 0.964
n_steps:
  value: 15
nr_of_clauses:
  value: 900
number_of_state_bits_ta:
  value: 4
specificity:
  value: 5.970000000000004
t:
  value: 0.54
update_freq:
  value: 2
y_max:
  value: 60
y_min:
  value: 30
