wandb_version: 1

batch_size:
  value: 48
bits_per_feature:
  value: 7
buffer_size:
  value: 6000
epochs:
  value: 2
gamma:
  value: 0.983
n_steps:
  value: 12
nr_of_clauses:
  value: 900
number_of_state_bits_ta:
  value: 3
specificity:
  value: 4.700000000000003
t:
  value: 0.39
update_freq:
  value: 9
y_max:
  value: 65
y_min:
  value: 35
