wandb_version: 1

batch_size:
  value: 16
bits_per_feature:
  value: 14
buffer_size:
  value: 5500
epochs:
  value: 6
gamma:
  value: 0.925
n_steps:
  value: 10
nr_of_clauses:
  value: 1000
number_of_state_bits_ta:
  value: 8
specificity:
  value: 2.520000000000002
t:
  value: 0.36000000000000004
update_freq:
  value: 8
y_max:
  value: 75
y_min:
  value: 35
