wandb_version: 1

batch_size:
  value: 16
bits_per_feature:
  value: 11
buffer_size:
  value: 7500
epochs:
  value: 2
gamma:
  value: 0.921
n_steps:
  value: 18
nr_of_clauses:
  value: 1120
number_of_state_bits_ta:
  value: 7
specificity:
  value: 6.460000000000004
t:
  value: 0.47
update_freq:
  value: 7
y_max:
  value: 75
y_min:
  value: 35
