wandb_version: 1

batch_size:
  value: 80
bits_per_feature:
  value: 10
buffer_size:
  value: 5500
epochs:
  value: 1
gamma:
  value: 0.934
n_steps:
  value: 12
nr_of_clauses:
  value: 1140
number_of_state_bits_ta:
  value: 6
specificity:
  value: 4.7100000000000035
t:
  value: 0.97
update_freq:
  value: 9
y_max:
  value: 75
y_min:
  value: 25
