wandb_version: 1

batch_size:
  value: 96
bits_per_feature:
  value: 6
buffer_size:
  value: 6000
epochs:
  value: 5
gamma:
  value: 0.993
n_steps:
  value: 14
nr_of_clauses:
  value: 1080
number_of_state_bits_ta:
  value: 3
specificity:
  value: 5.860000000000005
t:
  value: 0.5800000000000001
update_freq:
  value: 3
y_max:
  value: 75
y_min:
  value: 20
