wandb_version: 1

batch_size:
  value: 64
bits_per_feature:
  value: 13
buffer_size:
  value: 1500
epochs:
  value: 5
gamma:
  value: 0.963
n_steps:
  value: 19
nr_of_clauses:
  value: 880
number_of_state_bits_ta:
  value: 4
specificity:
  value: 9.340000000000009
t:
  value: 0.99
update_freq:
  value: 2
y_max:
  value: 65
y_min:
  value: 35
