wandb_version: 1

batch_size:
  value: 112
bits_per_feature:
  value: 6
buffer_size:
  value: 4000
epochs:
  value: 4
gamma:
  value: 0.928
n_steps:
  value: 8
nr_of_clauses:
  value: 940
number_of_state_bits_ta:
  value: 8
specificity:
  value: 9.160000000000007
t:
  value: 0.66
update_freq:
  value: 5
y_max:
  value: 75
y_min:
  value: 30
