wandb_version: 1

batch_size:
  value: 16
bits_per_feature:
  value: 14
buffer_size:
  value: 6000
epochs:
  value: 1
gamma:
  value: 0.907
n_steps:
  value: 4
nr_of_clauses:
  value: 1180
number_of_state_bits_ta:
  value: 4
specificity:
  value: 9.710000000000008
t:
  value: 0.01
update_freq:
  value: 9
y_max:
  value: 75
y_min:
  value: 25
