wandb_version: 1

batch_size:
  value: 80
bits_per_feature:
  value: 11
buffer_size:
  value: 9500
epochs:
  value: 5
gamma:
  value: 0.911
n_steps:
  value: 11
nr_of_clauses:
  value: 920
number_of_state_bits_ta:
  value: 9
specificity:
  value: 8.040000000000006
t:
  value: 0.93
update_freq:
  value: 4
y_max:
  value: 60
y_min:
  value: 30
