wandb_version: 1

batch_size:
  value: 32
bits_per_feature:
  value: 6
buffer_size:
  value: 4000
epochs:
  value: 1
gamma:
  value: 0.967
n_steps:
  value: 15
nr_of_clauses:
  value: 800
number_of_state_bits_ta:
  value: 9
specificity:
  value: 7.390000000000006
t:
  value: 0.81
update_freq:
  value: 5
y_max:
  value: 75
y_min:
  value: 25
