wandb_version: 1

batch_size:
  value: 80
bits_per_feature:
  value: 5
buffer_size:
  value: 3000
epochs:
  value: 6
gamma:
  value: 0.946
n_steps:
  value: 1
nr_of_clauses:
  value: 1160
number_of_state_bits_ta:
  value: 4
specificity:
  value: 2.8900000000000015
t:
  value: 0.26
update_freq:
  value: 8
y_max:
  value: 60
y_min:
  value: 25
