wandb_version: 1

batch_size:
  value: 96
bits_per_feature:
  value: 14
buffer_size:
  value: 2500
epochs:
  value: 3
gamma:
  value: 0.965
n_steps:
  value: 18
nr_of_clauses:
  value: 920
number_of_state_bits_ta:
  value: 9
specificity:
  value: 4.440000000000003
t:
  value: 0.18000000000000002
update_freq:
  value: 8
y_max:
  value: 65
y_min:
  value: 35
