wandb_version: 1

batch_size:
  value: 16
bits_per_feature:
  value: 7
buffer_size:
  value: 7500
epochs:
  value: 4
gamma:
  value: 0.979
n_steps:
  value: 5
nr_of_clauses:
  value: 1100
number_of_state_bits_ta:
  value: 7
specificity:
  value: 9.890000000000008
t:
  value: 0.24
update_freq:
  value: 3
y_max:
  value: 65
y_min:
  value: 25
