wandb_version: 1

batch_size:
  value: 80
bits_per_feature:
  value: 14
buffer_size:
  value: 9000
epochs:
  value: 4
gamma:
  value: 0.974
n_steps:
  value: 4
nr_of_clauses:
  value: 1020
number_of_state_bits_ta:
  value: 8
specificity:
  value: 4.100000000000003
t:
  value: 0.45
update_freq:
  value: 8
y_max:
  value: 60
y_min:
  value: 20
