wandb_version: 1

batch_size:
  value: 112
bits_per_feature:
  value: 6
buffer_size:
  value: 6000
epochs:
  value: 4
gamma:
  value: 0.976
n_steps:
  value: 6
nr_of_clauses:
  value: 1020
number_of_state_bits_ta:
  value: 9
specificity:
  value: 8.300000000000006
t:
  value: 0.17
update_freq:
  value: 3
y_max:
  value: 70
y_min:
  value: 25
