wandb_version: 1

batch_size:
  value: 16
bits_per_feature:
  value: 5
buffer_size:
  value: 9500
epochs:
  value: 5
gamma:
  value: 0.995
n_steps:
  value: 4
nr_of_clauses:
  value: 820
number_of_state_bits_ta:
  value: 7
specificity:
  value: 2.6300000000000017
t:
  value: 0.78
update_freq:
  value: 8
y_max:
  value: 70
y_min:
  value: 35
