wandb_version: 1

batch_size:
  value: 16
bits_per_feature:
  value: 5
buffer_size:
  value: 8000
epochs:
  value: 7
gamma:
  value: 0.979
n_steps:
  value: 4
nr_of_clauses:
  value: 1180
number_of_state_bits_ta:
  value: 5
specificity:
  value: 1.4800000000000004
t:
  value: 0.52
update_freq:
  value: 7
y_max:
  value: 60
y_min:
  value: 35
