wandb_version: 1

batch_size:
  value: 96
bits_per_feature:
  value: 6
buffer_size:
  value: 500
epochs:
  value: 6
gamma:
  value: 0.97
n_steps:
  value: 16
nr_of_clauses:
  value: 1020
number_of_state_bits_ta:
  value: 8
specificity:
  value: 5.430000000000004
t:
  value: 0.55
update_freq:
  value: 9
y_max:
  value: 60
y_min:
  value: 20
