wandb_version: 1

batch_size:
  value: 96
bits_per_feature:
  value: 12
buffer_size:
  value: 4500
epochs:
  value: 6
gamma:
  value: 0.902
n_steps:
  value: 12
nr_of_clauses:
  value: 980
number_of_state_bits_ta:
  value: 3
specificity:
  value: 5.460000000000004
t:
  value: 0.72
update_freq:
  value: 6
y_max:
  value: 75
y_min:
  value: 35
