wandb_version: 1

batch_size:
  value: 80
bits_per_feature:
  value: 6
buffer_size:
  value: 3000
epochs:
  value: 4
gamma:
  value: 0.922
n_steps:
  value: 13
nr_of_clauses:
  value: 1160
number_of_state_bits_ta:
  value: 8
specificity:
  value: 7.720000000000006
t:
  value: 0.42
update_freq:
  value: 8
y_max:
  value: 60
y_min:
  value: 35
