wandb_version: 1

batch_size:
  value: 80
bits_per_feature:
  value: 9
buffer_size:
  value: 4000
epochs:
  value: 2
gamma:
  value: 0.992
n_steps:
  value: 17
nr_of_clauses:
  value: 980
number_of_state_bits_ta:
  value: 6
specificity:
  value: 8.580000000000007
t:
  value: 0.34
update_freq:
  value: 8
y_max:
  value: 60
y_min:
  value: 20
