wandb_version: 1

batch_size:
  value: 16
bits_per_feature:
  value: 9
buffer_size:
  value: 1000
epochs:
  value: 2
gamma:
  value: 0.931
n_steps:
  value: 5
nr_of_clauses:
  value: 1160
number_of_state_bits_ta:
  value: 8
specificity:
  value: 2.0100000000000007
t:
  value: 0.36000000000000004
update_freq:
  value: 5
y_max:
  value: 65
y_min:
  value: 35
