wandb_version: 1

batch_size:
  value: 96
bits_per_feature:
  value: 6
buffer_size:
  value: 7500
epochs:
  value: 2
gamma:
  value: 0.981
n_steps:
  value: 1
nr_of_clauses:
  value: 1120
number_of_state_bits_ta:
  value: 8
specificity:
  value: 5.560000000000004
t:
  value: 0.2
update_freq:
  value: 5
y_max:
  value: 70
y_min:
  value: 25
