wandb_version: 1

batch_size:
  value: 16
bits_per_feature:
  value: 6
buffer_size:
  value: 2500
epochs:
  value: 5
gamma:
  value: 0.954
n_steps:
  value: 11
nr_of_clauses:
  value: 1000
number_of_state_bits_ta:
  value: 7
specificity:
  value: 9.140000000000008
t:
  value: 0.42
update_freq:
  value: 9
y_max:
  value: 65
y_min:
  value: 35
