wandb_version: 1

batch_size:
  value: 48
bits_per_feature:
  value: 8
buffer_size:
  value: 7500
epochs:
  value: 5
gamma:
  value: 0.99
n_steps:
  value: 8
nr_of_clauses:
  value: 1020
number_of_state_bits_ta:
  value: 6
specificity:
  value: 4.5000000000000036
t:
  value: 0.21
update_freq:
  value: 3
y_max:
  value: 75
y_min:
  value: 30
