wandb_version: 1

batch_size:
  value: 96
bits_per_feature:
  value: 7
buffer_size:
  value: 1500
epochs:
  value: 4
gamma:
  value: 0.927
n_steps:
  value: 9
nr_of_clauses:
  value: 1120
number_of_state_bits_ta:
  value: 9
specificity:
  value: 9.240000000000007
t:
  value: 0.76
update_freq:
  value: 9
y_max:
  value: 75
y_min:
  value: 30
