wandb_version: 1

batch_size:
  value: 112
bits_per_feature:
  value: 11
buffer_size:
  value: 4000
epochs:
  value: 1
gamma:
  value: 0.903
n_steps:
  value: 5
nr_of_clauses:
  value: 1020
number_of_state_bits_ta:
  value: 6
specificity:
  value: 6.710000000000005
t:
  value: 0.96
update_freq:
  value: 9
y_max:
  value: 65
y_min:
  value: 25
