wandb_version: 1

batch_size:
  value: 112
bits_per_feature:
  value: 13
buffer_size:
  value: 500
epochs:
  value: 5
gamma:
  value: 0.9
n_steps:
  value: 8
nr_of_clauses:
  value: 1000
number_of_state_bits_ta:
  value: 7
specificity:
  value: 3.530000000000002
t:
  value: 0.65
update_freq:
  value: 2
y_max:
  value: 75
y_min:
  value: 35
