wandb_version: 1

batch_size:
  value: 80
bits_per_feature:
  value: 7
buffer_size:
  value: 2000
epochs:
  value: 3
gamma:
  value: 0.912
n_steps:
  value: 13
nr_of_clauses:
  value: 1180
number_of_state_bits_ta:
  value: 4
specificity:
  value: 6.870000000000005
t:
  value: 0.38
update_freq:
  value: 4
y_max:
  value: 60
y_min:
  value: 30
