wandb_version: 1

batch_size:
  value: 48
bits_per_feature:
  value: 11
buffer_size:
  value: 7500
epochs:
  value: 5
gamma:
  value: 0.993
n_steps:
  value: 15
nr_of_clauses:
  value: 1020
number_of_state_bits_ta:
  value: 8
specificity:
  value: 6.440000000000005
t:
  value: 0.45
update_freq:
  value: 5
y_max:
  value: 65
y_min:
  value: 20
