wandb_version: 1

batch_size:
  value: 96
bits_per_feature:
  value: 6
buffer_size:
  value: 1500
epochs:
  value: 1
gamma:
  value: 0.935
n_steps:
  value: 10
nr_of_clauses:
  value: 900
number_of_state_bits_ta:
  value: 9
specificity:
  value: 7.000000000000005
t:
  value: 0.66
update_freq:
  value: 8
y_max:
  value: 75
y_min:
  value: 35
