wandb_version: 1

batch_size:
  value: 112
bits_per_feature:
  value: 13
buffer_size:
  value: 3500
epochs:
  value: 7
gamma:
  value: 0.989
n_steps:
  value: 8
nr_of_clauses:
  value: 960
number_of_state_bits_ta:
  value: 8
specificity:
  value: 4.890000000000003
t:
  value: 0.08
update_freq:
  value: 6
y_max:
  value: 65
y_min:
  value: 35
