wandb_version: 1

batch_size:
  value: 32
bits_per_feature:
  value: 8
buffer_size:
  value: 5000
epochs:
  value: 1
gamma:
  value: 0.96
n_steps:
  value: 19
nr_of_clauses:
  value: 1040
number_of_state_bits_ta:
  value: 3
specificity:
  value: 1.02
t:
  value: 0.5800000000000001
update_freq:
  value: 9
y_max:
  value: 70
y_min:
  value: 20
