wandb_version: 1

batch_size:
  value: 48
bits_per_feature:
  value: 13
buffer_size:
  value: 7500
epochs:
  value: 2
gamma:
  value: 0.933
n_steps:
  value: 11
nr_of_clauses:
  value: 1120
number_of_state_bits_ta:
  value: 9
specificity:
  value: 5.1300000000000034
t:
  value: 0.32
update_freq:
  value: 4
y_max:
  value: 60
y_min:
  value: 35
