wandb_version: 1

batch_size:
  value: 32
bits_per_feature:
  value: 10
buffer_size:
  value: 4000
epochs:
  value: 5
gamma:
  value: 0.983
n_steps:
  value: 4
nr_of_clauses:
  value: 1140
number_of_state_bits_ta:
  value: 4
specificity:
  value: 3.8500000000000023
t:
  value: 0.5700000000000001
update_freq:
  value: 7
y_max:
  value: 75
y_min:
  value: 20
