wandb_version: 1

batch_size:
  value: 48
bits_per_feature:
  value: 9
buffer_size:
  value: 1500
epochs:
  value: 3
gamma:
  value: 0.909
n_steps:
  value: 18
nr_of_clauses:
  value: 1000
number_of_state_bits_ta:
  value: 7
specificity:
  value: 5.080000000000004
t:
  value: 0.59
update_freq:
  value: 7
y_max:
  value: 60
y_min:
  value: 35
