wandb_version: 1

batch_size:
  value: 16
bits_per_feature:
  value: 7
buffer_size:
  value: 6000
epochs:
  value: 7
gamma:
  value: 0.942
n_steps:
  value: 4
nr_of_clauses:
  value: 940
number_of_state_bits_ta:
  value: 3
specificity:
  value: 6.930000000000005
t:
  value: 0.8400000000000001
update_freq:
  value: 5
y_max:
  value: 60
y_min:
  value: 35
