wandb_version: 1

batch_size:
  value: 80
bits_per_feature:
  value: 7
buffer_size:
  value: 8000
epochs:
  value: 2
gamma:
  value: 0.977
n_steps:
  value: 19
nr_of_clauses:
  value: 980
number_of_state_bits_ta:
  value: 5
specificity:
  value: 6.560000000000005
t:
  value: 0.51
update_freq:
  value: 7
y_max:
  value: 60
y_min:
  value: 25
