wandb_version: 1

batch_size:
  value: 80
bits_per_feature:
  value: 8
buffer_size:
  value: 3000
epochs:
  value: 1
gamma:
  value: 0.961
n_steps:
  value: 18
nr_of_clauses:
  value: 800
number_of_state_bits_ta:
  value: 3
specificity:
  value: 7.880000000000006
t:
  value: 0.7000000000000001
update_freq:
  value: 2
y_max:
  value: 60
y_min:
  value: 35
