wandb_version: 1

batch_size:
  value: 80
bits_per_feature:
  value: 12
buffer_size:
  value: 1500
epochs:
  value: 5
gamma:
  value: 0.909
n_steps:
  value: 4
nr_of_clauses:
  value: 920
number_of_state_bits_ta:
  value: 7
specificity:
  value: 5.220000000000004
t:
  value: 0.88
update_freq:
  value: 6
y_max:
  value: 65
y_min:
  value: 30
