wandb_version: 1

batch_size:
  value: 80
bits_per_feature:
  value: 6
buffer_size:
  value: 4500
epochs:
  value: 6
gamma:
  value: 0.981
n_steps:
  value: 14
nr_of_clauses:
  value: 960
number_of_state_bits_ta:
  value: 7
specificity:
  value: 1.5100000000000005
t:
  value: 0.8
update_freq:
  value: 6
y_max:
  value: 75
y_min:
  value: 20
