wandb_version: 1

batch_size:
  value: 16
bits_per_feature:
  value: 14
buffer_size:
  value: 2500
epochs:
  value: 4
gamma:
  value: 0.968
n_steps:
  value: 17
nr_of_clauses:
  value: 1120
number_of_state_bits_ta:
  value: 9
specificity:
  value: 2.6900000000000013
t:
  value: 0.67
update_freq:
  value: 7
y_max:
  value: 60
y_min:
  value: 20
