wandb_version: 1

batch_size:
  value: 96
bits_per_feature:
  value: 13
buffer_size:
  value: 7500
epochs:
  value: 3
gamma:
  value: 0.911
n_steps:
  value: 10
nr_of_clauses:
  value: 1000
number_of_state_bits_ta:
  value: 7
specificity:
  value: 9.170000000000009
t:
  value: 0.55
update_freq:
  value: 7
y_max:
  value: 60
y_min:
  value: 25
