wandb_version: 1

batch_size:
  value: 48
bits_per_feature:
  value: 6
buffer_size:
  value: 3000
epochs:
  value: 2
gamma:
  value: 0.961
n_steps:
  value: 12
nr_of_clauses:
  value: 1120
number_of_state_bits_ta:
  value: 5
specificity:
  value: 9.920000000000009
t:
  value: 0.63
update_freq:
  value: 7
y_max:
  value: 75
y_min:
  value: 35
