wandb_version: 1

batch_size:
  value: 16
bits_per_feature:
  value: 6
buffer_size:
  value: 500
epochs:
  value: 3
gamma:
  value: 0.959
n_steps:
  value: 15
nr_of_clauses:
  value: 1060
number_of_state_bits_ta:
  value: 6
specificity:
  value: 5.960000000000004
t:
  value: 0.94
update_freq:
  value: 8
y_max:
  value: 70
y_min:
  value: 35
