wandb_version: 1

batch_size:
  value: 32
bits_per_feature:
  value: 11
buffer_size:
  value: 2500
epochs:
  value: 3
gamma:
  value: 0.947
n_steps:
  value: 16
nr_of_clauses:
  value: 880
number_of_state_bits_ta:
  value: 9
specificity:
  value: 6.230000000000005
t:
  value: 0.36000000000000004
update_freq:
  value: 2
y_max:
  value: 70
y_min:
  value: 35
