wandb_version: 1

batch_size:
  value: 96
bits_per_feature:
  value: 10
buffer_size:
  value: 8000
epochs:
  value: 5
gamma:
  value: 0.995
n_steps:
  value: 3
nr_of_clauses:
  value: 1060
number_of_state_bits_ta:
  value: 9
specificity:
  value: 3.160000000000002
t:
  value: 0.34
update_freq:
  value: 4
y_max:
  value: 60
y_min:
  value: 30
