wandb_version: 1

batch_size:
  value: 16
bits_per_feature:
  value: 6
buffer_size:
  value: 3500
epochs:
  value: 1
gamma:
  value: 0.952
n_steps:
  value: 11
nr_of_clauses:
  value: 940
number_of_state_bits_ta:
  value: 3
specificity:
  value: 3.9700000000000024
t:
  value: 0.41
update_freq:
  value: 7
y_max:
  value: 75
y_min:
  value: 20
