wandb_version: 1

batch_size:
  value: 32
bits_per_feature:
  value: 11
buffer_size:
  value: 2000
epochs:
  value: 3
gamma:
  value: 0.969
n_steps:
  value: 1
nr_of_clauses:
  value: 1140
number_of_state_bits_ta:
  value: 4
specificity:
  value: 6.280000000000005
t:
  value: 0.95
update_freq:
  value: 2
y_max:
  value: 75
y_min:
  value: 35
