wandb_version: 1

batch_size:
  value: 32
bits_per_feature:
  value: 13
buffer_size:
  value: 8000
epochs:
  value: 1
gamma:
  value: 0.934
n_steps:
  value: 9
nr_of_clauses:
  value: 940
number_of_state_bits_ta:
  value: 8
specificity:
  value: 2.330000000000001
t:
  value: 0.46
update_freq:
  value: 7
y_max:
  value: 70
y_min:
  value: 35
