wandb_version: 1

batch_size:
  value: 32
bits_per_feature:
  value: 10
buffer_size:
  value: 500
epochs:
  value: 7
gamma:
  value: 0.989
n_steps:
  value: 2
nr_of_clauses:
  value: 1060
number_of_state_bits_ta:
  value: 4
specificity:
  value: 7.980000000000006
t:
  value: 0.38
update_freq:
  value: 7
y_max:
  value: 75
y_min:
  value: 35
