wandb_version: 1

batch_size:
  value: 112
bits_per_feature:
  value: 11
buffer_size:
  value: 6500
epochs:
  value: 1
gamma:
  value: 0.95
n_steps:
  value: 18
nr_of_clauses:
  value: 880
number_of_state_bits_ta:
  value: 8
specificity:
  value: 1.02
t:
  value: 0.75
update_freq:
  value: 5
y_max:
  value: 70
y_min:
  value: 35
