wandb_version: 1

batch_size:
  value: 48
bits_per_feature:
  value: 10
buffer_size:
  value: 2500
epochs:
  value: 4
gamma:
  value: 0.997
n_steps:
  value: 13
nr_of_clauses:
  value: 840
number_of_state_bits_ta:
  value: 5
specificity:
  value: 7.680000000000006
t:
  value: 0.73
update_freq:
  value: 4
y_max:
  value: 65
y_min:
  value: 35
