wandb_version: 1

batch_size:
  value: 96
bits_per_feature:
  value: 14
buffer_size:
  value: 1500
epochs:
  value: 3
gamma:
  value: 0.998
n_steps:
  value: 19
nr_of_clauses:
  value: 900
number_of_state_bits_ta:
  value: 8
specificity:
  value: 7.730000000000006
t:
  value: 0.78
update_freq:
  value: 2
y_max:
  value: 70
y_min:
  value: 20
