wandb_version: 1

batch_size:
  value: 64
bits_per_feature:
  value: 11
buffer_size:
  value: 2000
epochs:
  value: 7
gamma:
  value: 0.933
n_steps:
  value: 19
nr_of_clauses:
  value: 940
number_of_state_bits_ta:
  value: 4
specificity:
  value: 3.710000000000002
t:
  value: 0.53
update_freq:
  value: 4
y_max:
  value: 70
y_min:
  value: 25
