wandb_version: 1

batch_size:
  value: 96
bits_per_feature:
  value: 11
buffer_size:
  value: 4000
epochs:
  value: 5
gamma:
  value: 0.973
n_steps:
  value: 8
nr_of_clauses:
  value: 1100
number_of_state_bits_ta:
  value: 8
specificity:
  value: 4.450000000000003
t:
  value: 0.31
update_freq:
  value: 8
y_max:
  value: 65
y_min:
  value: 30
