wandb_version: 1

batch_size:
  value: 96
bits_per_feature:
  value: 10
buffer_size:
  value: 6000
epochs:
  value: 7
gamma:
  value: 0.966
n_steps:
  value: 18
nr_of_clauses:
  value: 840
number_of_state_bits_ta:
  value: 4
specificity:
  value: 3.7600000000000025
t:
  value: 0.5700000000000001
update_freq:
  value: 6
y_max:
  value: 70
y_min:
  value: 20
