wandb_version: 1

batch_size:
  value: 16
bits_per_feature:
  value: 13
buffer_size:
  value: 2000
epochs:
  value: 1
gamma:
  value: 0.93
n_steps:
  value: 13
nr_of_clauses:
  value: 820
number_of_state_bits_ta:
  value: 5
specificity:
  value: 6.320000000000005
t:
  value: 0.12
update_freq:
  value: 9
y_max:
  value: 70
y_min:
  value: 35
