wandb_version: 1

batch_size:
  value: 112
bits_per_feature:
  value: 13
buffer_size:
  value: 5500
epochs:
  value: 3
gamma:
  value: 0.941
n_steps:
  value: 5
nr_of_clauses:
  value: 1100
number_of_state_bits_ta:
  value: 8
specificity:
  value: 7.270000000000006
t:
  value: 0.64
update_freq:
  value: 6
y_max:
  value: 65
y_min:
  value: 35
