wandb_version: 1

batch_size:
  value: 112
bits_per_feature:
  value: 12
buffer_size:
  value: 3000
epochs:
  value: 5
gamma:
  value: 0.961
n_steps:
  value: 6
nr_of_clauses:
  value: 860
number_of_state_bits_ta:
  value: 3
specificity:
  value: 1.7000000000000006
t:
  value: 0.5
update_freq:
  value: 8
y_max:
  value: 65
y_min:
  value: 35
