wandb_version: 1

batch_size:
  value: 32
bits_per_feature:
  value: 7
buffer_size:
  value: 500
epochs:
  value: 3
gamma:
  value: 0.928
n_steps:
  value: 18
nr_of_clauses:
  value: 840
number_of_state_bits_ta:
  value: 3
specificity:
  value: 6.820000000000006
t:
  value: 0.09
update_freq:
  value: 3
y_max:
  value: 60
y_min:
  value: 30
