wandb_version: 1

batch_size:
  value: 96
bits_per_feature:
  value: 12
buffer_size:
  value: 8000
epochs:
  value: 5
gamma:
  value: 0.918
n_steps:
  value: 19
nr_of_clauses:
  value: 1180
number_of_state_bits_ta:
  value: 9
specificity:
  value: 1.7400000000000009
t:
  value: 0.03
update_freq:
  value: 9
y_max:
  value: 75
y_min:
  value: 20
