wandb_version: 1

batch_size:
  value: 96
bits_per_feature:
  value: 7
buffer_size:
  value: 500
epochs:
  value: 7
gamma:
  value: 0.975
n_steps:
  value: 16
nr_of_clauses:
  value: 880
number_of_state_bits_ta:
  value: 5
specificity:
  value: 5.6200000000000045
t:
  value: 0.75
update_freq:
  value: 4
y_max:
  value: 60
y_min:
  value: 35
