wandb_version: 1

batch_size:
  value: 96
bits_per_feature:
  value: 11
buffer_size:
  value: 7000
epochs:
  value: 1
gamma:
  value: 0.986
n_steps:
  value: 11
nr_of_clauses:
  value: 860
number_of_state_bits_ta:
  value: 3
specificity:
  value: 6.0800000000000045
t:
  value: 0.13
update_freq:
  value: 2
y_max:
  value: 65
y_min:
  value: 20
