wandb_version: 1

batch_size:
  value: 32
bits_per_feature:
  value: 8
buffer_size:
  value: 500
epochs:
  value: 4
gamma:
  value: 0.98
n_steps:
  value: 14
nr_of_clauses:
  value: 980
number_of_state_bits_ta:
  value: 6
specificity:
  value: 2.9600000000000017
t:
  value: 0.5700000000000001
update_freq:
  value: 9
y_max:
  value: 70
y_min:
  value: 25
