wandb_version: 1

batch_size:
  value: 48
bits_per_feature:
  value: 10
buffer_size:
  value: 5000
epochs:
  value: 6
gamma:
  value: 0.996
n_steps:
  value: 14
nr_of_clauses:
  value: 1180
number_of_state_bits_ta:
  value: 3
specificity:
  value: 8.510000000000007
t:
  value: 0.24
update_freq:
  value: 6
y_max:
  value: 75
y_min:
  value: 30
