wandb_version: 1

batch_size:
  value: 96
bits_per_feature:
  value: 9
buffer_size:
  value: 6500
epochs:
  value: 1
gamma:
  value: 0.902
n_steps:
  value: 18
nr_of_clauses:
  value: 880
number_of_state_bits_ta:
  value: 3
specificity:
  value: 7.2000000000000055
t:
  value: 0.02
update_freq:
  value: 3
y_max:
  value: 75
y_min:
  value: 35
