wandb_version: 1

batch_size:
  value: 16
bits_per_feature:
  value: 9
buffer_size:
  value: 2500
epochs:
  value: 5
gamma:
  value: 0.956
n_steps:
  value: 11
nr_of_clauses:
  value: 880
number_of_state_bits_ta:
  value: 3
specificity:
  value: 9.170000000000009
t:
  value: 0.54
update_freq:
  value: 7
y_max:
  value: 60
y_min:
  value: 35
