wandb_version: 1

batch_size:
  value: 48
bits_per_feature:
  value: 5
buffer_size:
  value: 9000
epochs:
  value: 7
gamma:
  value: 0.978
n_steps:
  value: 17
nr_of_clauses:
  value: 980
number_of_state_bits_ta:
  value: 3
specificity:
  value: 7.310000000000006
t:
  value: 0.87
update_freq:
  value: 9
y_max:
  value: 70
y_min:
  value: 25
