wandb_version: 1

batch_size:
  value: 32
bits_per_feature:
  value: 13
buffer_size:
  value: 1000
epochs:
  value: 4
gamma:
  value: 0.949
n_steps:
  value: 12
nr_of_clauses:
  value: 880
number_of_state_bits_ta:
  value: 6
specificity:
  value: 1.8400000000000007
t:
  value: 0.2
update_freq:
  value: 7
y_max:
  value: 60
y_min:
  value: 30
