wandb_version: 1

batch_size:
  value: 16
bits_per_feature:
  value: 6
buffer_size:
  value: 9000
epochs:
  value: 6
gamma:
  value: 0.914
n_steps:
  value: 19
nr_of_clauses:
  value: 1140
number_of_state_bits_ta:
  value: 8
specificity:
  value: 8.280000000000006
t:
  value: 0.75
update_freq:
  value: 2
y_max:
  value: 65
y_min:
  value: 20
