wandb_version: 1

batch_size:
  value: 64
bits_per_feature:
  value: 10
buffer_size:
  value: 2500
epochs:
  value: 7
gamma:
  value: 0.916
n_steps:
  value: 8
nr_of_clauses:
  value: 880
number_of_state_bits_ta:
  value: 9
specificity:
  value: 4.730000000000003
t:
  value: 0.24
update_freq:
  value: 2
y_max:
  value: 65
y_min:
  value: 35
