wandb_version: 1

batch_size:
  value: 48
bits_per_feature:
  value: 8
buffer_size:
  value: 5500
epochs:
  value: 6
gamma:
  value: 0.954
n_steps:
  value: 15
nr_of_clauses:
  value: 1000
number_of_state_bits_ta:
  value: 7
specificity:
  value: 2.410000000000001
t:
  value: 0.5800000000000001
update_freq:
  value: 4
y_max:
  value: 75
y_min:
  value: 35
