wandb_version: 1

batch_size:
  value: 112
bits_per_feature:
  value: 6
buffer_size:
  value: 6500
epochs:
  value: 2
gamma:
  value: 0.965
n_steps:
  value: 3
nr_of_clauses:
  value: 840
number_of_state_bits_ta:
  value: 8
specificity:
  value: 9.100000000000009
t:
  value: 0.48
update_freq:
  value: 3
y_max:
  value: 65
y_min:
  value: 20
