wandb_version: 1

batch_size:
  value: 64
bits_per_feature:
  value: 6
buffer_size:
  value: 7500
epochs:
  value: 1
gamma:
  value: 0.911
n_steps:
  value: 10
nr_of_clauses:
  value: 1060
number_of_state_bits_ta:
  value: 4
specificity:
  value: 9.400000000000007
t:
  value: 0.49
update_freq:
  value: 7
y_max:
  value: 60
y_min:
  value: 25
