wandb_version: 1

batch_size:
  value: 80
bits_per_feature:
  value: 8
buffer_size:
  value: 3500
epochs:
  value: 6
gamma:
  value: 0.942
n_steps:
  value: 3
nr_of_clauses:
  value: 940
number_of_state_bits_ta:
  value: 7
specificity:
  value: 3.140000000000002
t:
  value: 0.63
update_freq:
  value: 3
y_max:
  value: 65
y_min:
  value: 20
