wandb_version: 1

batch_size:
  value: 64
bits_per_feature:
  value: 12
buffer_size:
  value: 8500
epochs:
  value: 3
gamma:
  value: 0.973
n_steps:
  value: 4
nr_of_clauses:
  value: 1060
number_of_state_bits_ta:
  value: 3
specificity:
  value: 1.9900000000000009
t:
  value: 0.45
update_freq:
  value: 8
y_max:
  value: 75
y_min:
  value: 30
