wandb_version: 1

batch_size:
  value: 32
bits_per_feature:
  value: 9
buffer_size:
  value: 9500
epochs:
  value: 2
gamma:
  value: 0.955
n_steps:
  value: 19
nr_of_clauses:
  value: 1080
number_of_state_bits_ta:
  value: 9
specificity:
  value: 5.740000000000004
t:
  value: 0.67
update_freq:
  value: 5
y_max:
  value: 70
y_min:
  value: 25
