wandb_version: 1

batch_size:
  value: 112
bits_per_feature:
  value: 10
buffer_size:
  value: 8000
epochs:
  value: 6
gamma:
  value: 0.902
n_steps:
  value: 8
nr_of_clauses:
  value: 1160
number_of_state_bits_ta:
  value: 7
specificity:
  value: 4.890000000000003
t:
  value: 0.8200000000000001
update_freq:
  value: 6
y_max:
  value: 70
y_min:
  value: 35
