wandb_version: 1

batch_size:
  value: 96
bits_per_feature:
  value: 10
buffer_size:
  value: 3000
epochs:
  value: 3
gamma:
  value: 0.97
n_steps:
  value: 10
nr_of_clauses:
  value: 860
number_of_state_bits_ta:
  value: 9
specificity:
  value: 5.140000000000004
t:
  value: 0.4
update_freq:
  value: 7
y_max:
  value: 70
y_min:
  value: 35
