wandb_version: 1

batch_size:
  value: 112
bits_per_feature:
  value: 8
buffer_size:
  value: 500
epochs:
  value: 3
gamma:
  value: 0.91
n_steps:
  value: 2
nr_of_clauses:
  value: 800
number_of_state_bits_ta:
  value: 6
specificity:
  value: 4.000000000000003
t:
  value: 0.88
update_freq:
  value: 9
y_max:
  value: 75
y_min:
  value: 35
