wandb_version: 1

batch_size:
  value: 32
bits_per_feature:
  value: 14
buffer_size:
  value: 4500
epochs:
  value: 1
gamma:
  value: 0.974
n_steps:
  value: 15
nr_of_clauses:
  value: 840
number_of_state_bits_ta:
  value: 9
specificity:
  value: 2.130000000000001
t:
  value: 0.35000000000000003
update_freq:
  value: 3
y_max:
  value: 60
y_min:
  value: 20
