wandb_version: 1

batch_size:
  value: 112
bits_per_feature:
  value: 5
buffer_size:
  value: 1500
epochs:
  value: 3
gamma:
  value: 0.969
n_steps:
  value: 7
nr_of_clauses:
  value: 1120
number_of_state_bits_ta:
  value: 5
specificity:
  value: 1.7200000000000006
t:
  value: 0.39
update_freq:
  value: 2
y_max:
  value: 65
y_min:
  value: 30
