T: 270
algorithm: TMQN
batch_size: 112
bits_per_feature: 13
buffer_size: 5500
device: CPU
epochs: 3
exploration_prob_decay: 0.001
exploration_prob_init: 1.0
gamma: 0.992
nr_of_clauses: 1040
nr_of_episodes: 10000
nr_of_steps: 3676751
number_of_state_bits_ta: 8
s: 8.9
save: true
seed: 42
test_freq: 1
weighted_clauses: false
y_max: 75
y_min: 20
