wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1707263098.865641
    t:
      1:
      - 1
      - 55
      3:
      - 23
      4: 3.10.0
      5: 0.16.3
      8:
      - 3
      - 5
      13: windows-amd64
gamma:
  desc: null
  value: 0.8319047078680156
nr_of_clauses:
  desc: null
  value: 1612
number_of_state_bits_ta:
  desc: null
  value: 7
specificity:
  desc: null
  value: 6.278534786697612
threshold:
  desc: null
  value: 0.6535398193937324
total_bits_per_feature:
  desc: null
  value: 9
update_freq:
  desc: null
  value: 30
y_max:
  desc: null
  value: 73
y_min:
  desc: null
  value: 36
