action_space_size: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  AwAAAAAAAAA=
actor:
  T: 1618
  bits_per_feature: 7
  device: CPU
  nr_of_clauses: 1760
  number_of_state_bits_ta: 6
  s: 2.99
  seed: 42
algorithm: TAC_b
batch_size: 1
buffer_size: 10000
critic:
  T: 1539
  bits_per_feature: 6
  device: CPU
  max_update_p: 0.008
  nr_of_clauses: 1750
  number_of_state_bits_ta: 5
  s: 3.370000000000006
  seed: 42
  weighted_clauses: false
  y_max: 0
  y_min: -40
dataset_file_name: acrobot_obs_data
env_name: acrobot
epsilon_decay: 0.001
epsilon_init: 1.0
gamma: 0.982
obs_space_size: 6
sampling_iterations: 64
save: true
soft_update_type: soft_update_b
test_freq: 1
threshold: -495
update_freq: 4
