T: 1050
action_space_size: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  AgAAAAAAAAA=
algorithm: Double_QTM_a
batch_size: 96
bits_per_feature: 10
buffer_size: 6500
dataset_file_name: observation_data
device: CPU
env_name: cartpole
epochs: 5
exploration_prob_decay: 0.007
exploration_prob_init: 0.9
gamma: 0.976
max_update_p: 0.178
min_update_p: 0
nr_of_clauses: 1180
number_of_state_bits_ta: 6
obs_space_size: 4
s: 6.210000000000004
save: true
seed: 42
soft_update_type: soft_update_1
test_freq: 1
threshold: 20
update_freq: -1
update_grad: 0.618
weighted_clauses: false
y_max: 75
y_min: 20
