wandb_version: 1

gamma:
  value: 0.9103861346692576
nr_of_clauses:
  value: 1000
number_of_state_bits_ta:
  value: 24
specificity:
  value: 4.258990807778
threshold:
  value: 0.3673925626570628
total_bits_per_feature:
  value: 11
update_freq:
  value: 18
y_max:
  value: 66
y_min:
  value: 23
