T: 765
algorithm: TM_PPO
batch_size: 208
bits_per_feature: 7
clip: 0.451
comment: --Does not use normalization--
device: CPU
epochs: 3
gamma: 0.954
lam: 0.941
nr_of_clauses: 1160
number_of_state_bits_ta: 4
s: 1.97
save: true
seed: 42
test_freq: 1
weighted_clauses: false
y_max: 2.0
y_min: 0.0
