action_space_size: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  AwAAAAAAAAA=
actor:
  T: 1343
  bits_per_feature: 13
  device: CPU
  nr_of_clauses: 1840
  number_of_state_bits_ta: 8
  s: 1.01
  seed: 42
  weighted_clauses: false
algorithm: TAC_a
batch_size: 48
buffer_size: 9500
critic:
  T: 1406
  bits_per_feature: 13
  device: CPU
  max_update_p: 0.078
  nr_of_clauses: 1850
  number_of_state_bits_ta: 9
  s: 3.290000000000002
  seed: 42
  weighted_clauses: false
  y_max: -5
  y_min: -80
dataset_file_name: acrobot_obs_data
env_name: acrobot
epochs: 2
exploration_prob_decay: 0.006
exploration_prob_init: 0.8999999999999999
gamma: 0.943
obs_space_size: 6
save: true
soft_update_type: soft_update_1
test_freq: 1
threshold: -495
update_grad: 0.749
