wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709006530.270732
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.0
      5: 0.16.3
      8:
      - 3
      - 5
      13: windows-amd64
a_bits_per_feature:
  desc: null
  value: 11
a_nr_of_clauses:
  desc: null
  value: 1040
a_number_of_state_bits_ta:
  desc: null
  value: 4
a_specificity:
  desc: null
  value: 4.820000000000004
a_t:
  desc: null
  value: 0.38
c_bits_per_feature:
  desc: null
  value: 5
c_nr_of_clauses:
  desc: null
  value: 1400
c_number_of_state_bits_ta:
  desc: null
  value: 5
c_specificity:
  desc: null
  value: 1.6400000000000006
c_t:
  desc: null
  value: 0.79
c_y_max:
  desc: null
  value: 65
c_y_min:
  desc: null
  value: 35
gamma:
  desc: null
  value: 0.947
update_freq:
  desc: null
  value: 4
