wandb_version: 1

a_bits_per_feature:
  value: 14
a_nr_of_clauses:
  value: 800
a_number_of_state_bits_ta:
  value: 3
a_specificity:
  value: 4.990000000000004
a_t:
  value: 0.28
c_bits_per_feature:
  value: 8
c_nr_of_clauses:
  value: 1100
c_number_of_state_bits_ta:
  value: 8
c_specificity:
  value: 1.7400000000000009
c_t:
  value: 0.5
c_y_max:
  value: 75
c_y_min:
  value: 20
gamma:
  value: 0.906
update_freq:
  value: 6
