wandb_version: 1

a_bits_per_feature:
  value: 9
a_nr_of_clauses:
  value: 920
a_number_of_state_bits_ta:
  value: 8
a_specificity:
  value: 1.08
a_t:
  value: 0.52
c_bits_per_feature:
  value: 12
c_nr_of_clauses:
  value: 1750
c_number_of_state_bits_ta:
  value: 4
c_specificity:
  value: 7.140000000000006
c_t:
  value: 0.36000000000000004
c_y_max:
  value: 70
c_y_min:
  value: 20
gamma:
  value: 0.982
update_freq:
  value: 3
