wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1708994077.415122
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.0
      5: 0.16.3
      8:
      - 3
      - 5
      13: windows-amd64
a_bits_per_feature:
  desc: null
  value: 7
a_nr_of_clauses:
  desc: null
  value: 1000
a_number_of_state_bits_ta:
  desc: null
  value: 4
a_specificity:
  desc: null
  value: 5.700000000000005
a_t:
  desc: null
  value: 0.9
c_bits_per_feature:
  desc: null
  value: 6
c_nr_of_clauses:
  desc: null
  value: 1300
c_number_of_state_bits_ta:
  desc: null
  value: 9
c_specificity:
  desc: null
  value: 6.130000000000004
c_t:
  desc: null
  value: 0.77
c_y_max:
  desc: null
  value: 75
c_y_min:
  desc: null
  value: 25
gamma:
  desc: null
  value: 0.923
update_freq:
  desc: null
  value: 6
